import type { ChallengeSeed } from "./shared";

export const functions: ChallengeSeed[] = [
  {
    slug: "calculator-function",
    title: "Calculator Function",
    category: "Functions",
    difficulty: "easy",
    skills: ["functions"],
    description: 'Write calculate(a, b, operator) supporting "+", "-", "*", "/".',
    examples: ['calculate(4, 2, "+") → 6', 'calculate(4, 2, "/") → 2'],
    starterCode: `function calculate(a, b, operator) {\n  // your code\n}`,
    tests: [
      { description: "adds two numbers", assertion: 'expect(calculate(4, 2, "+")).toBe(6)' },
      { description: "divides two numbers", assertion: 'expect(calculate(4, 2, "/")).toBe(2)' },
      { description: "multiplies two numbers", assertion: 'expect(calculate(4, 2, "*")).toBe(8)' },
      { hidden: true, description: "subtracts two numbers", assertion: 'expect(calculate(4, 2, "-")).toBe(2)' },
    ],
    hints: ["A switch statement on the operator keeps each branch simple and readable."],
    solution: `function calculate(a, b, operator) {\n  switch (operator) {\n    case "+": return a + b;\n    case "-": return a - b;\n    case "*": return a * b;\n    case "/": return a / b;\n    default: throw new Error("Unknown operator");\n  }\n}`,
    explanation: "A switch on the operator string is the clearest way to dispatch between four distinct behaviors.",
    relatedConcepts: ["Function declarations", "Conditions & branching"],
  },
  {
    slug: "callback-exercise",
    title: "Callback Exercise",
    category: "Functions",
    difficulty: "easy",
    skills: ["functions"],
    description: "Write applyOperation(a, b, callback) that calls callback with a and b and returns the result.",
    examples: ["applyOperation(3, 4, (x, y) => x + y) → 7"],
    starterCode: `function applyOperation(a, b, callback) {\n  // your code\n}`,
    tests: [
      { description: "runs an addition callback", assertion: "expect(applyOperation(3, 4, (x, y) => x + y)).toBe(7)" },
      { description: "runs a multiplication callback", assertion: "expect(applyOperation(3, 4, (x, y) => x * y)).toBe(12)" },
      { hidden: true, description: "runs a callback that ignores one argument", assertion: "expect(applyOperation(3, 4, (x) => x)).toBe(3)" },
    ],
    hints: ["Call the callback with (a, b) and return whatever it returns."],
    solution: `function applyOperation(a, b, callback) {\n  return callback(a, b);\n}`,
    explanation: "A callback is just a function passed as a value — applyOperation stays agnostic about what operation actually runs.",
    relatedConcepts: ["Higher-order functions"],
  },
  {
    slug: "higher-order-function",
    title: "Higher-Order Function",
    category: "Functions",
    difficulty: "medium",
    skills: ["functions"],
    description: "Write withCallCount(fn) returning a wrapped function that tracks how many times it has been called via a .calls property.",
    examples: ["const wrapped = withCallCount(fn); wrapped(); wrapped(); wrapped.calls → 2"],
    starterCode: `function withCallCount(fn) {\n  // your code\n}`,
    tests: [
      { description: "starts at zero calls", assertion: "const w = withCallCount(() => {}); expect(w.calls).toBe(0)" },
      { description: "counts two calls", assertion: "const w = withCallCount(() => {}); w(); w(); expect(w.calls).toBe(2)" },
      { hidden: true, description: "still returns the wrapped function's result", assertion: 'const w = withCallCount((x) => x * 2); expect(w(5)).toBe(10)' },
    ],
    hints: ["Attach a mutable `calls` property to the returned wrapper function and increment it on every call."],
    solution: `function withCallCount(fn) {\n  function wrapper(...args) {\n    wrapper.calls++;\n    return fn(...args);\n  }\n  wrapper.calls = 0;\n  return wrapper;\n}`,
    explanation: "Functions are objects too, so attaching a .calls property to the wrapper is completely valid and a common pattern.",
    relatedConcepts: ["Higher-order functions", "Closures"],
  },
  {
    slug: "function-composition",
    title: "Function Composition",
    category: "Functions",
    difficulty: "medium",
    skills: ["functions"],
    description: "Write compose(...fns) returning a function that applies the given functions right-to-left.",
    examples: ["compose(double, addOne)(3) → double(addOne(3)) → 8"],
    starterCode: `function compose(...fns) {\n  // your code\n}`,
    tests: [
      { description: "composes two functions right-to-left", assertion: "const double = (x) => x * 2; const addOne = (x) => x + 1; expect(compose(double, addOne)(3)).toBe(8)" },
      { description: "composing a single function behaves like calling it directly", assertion: "const square = (x) => x * x; expect(compose(square)(4)).toBe(16)" },
      { hidden: true, description: "composes three functions", assertion: "const inc = (x) => x + 1; expect(compose(inc, inc, inc)(0)).toBe(3)" },
    ],
    hints: ["reduceRight applies functions from the last argument to the first, matching right-to-left composition."],
    solution: `function compose(...fns) {\n  return (input) => fns.reduceRight((value, fn) => fn(value), input);\n}`,
    explanation: "reduceRight naturally expresses 'apply the rightmost function first, then feed its result to the next one left'.",
    relatedConcepts: ["Higher-order functions", "reduce, sort & analysis"],
  },
  {
    slug: "custom-map",
    title: "Custom Map",
    category: "Functions",
    difficulty: "medium",
    skills: ["functions", "arrays"],
    description: "Reimplement Array.prototype.map as myMap(array, callback) without using the built-in .map.",
    examples: ["myMap([1,2,3], x => x * 2) → [2,4,6]"],
    starterCode: `function myMap(array, callback) {\n  // your code — do not use array.map\n}`,
    tests: [
      { description: "doubles every element", assertion: "expect(myMap([1, 2, 3], (x) => x * 2)).toEqual([2, 4, 6])" },
      { description: "passes the index to the callback", assertion: "expect(myMap([10, 20], (x, i) => i)).toEqual([0, 1])" },
      { hidden: true, description: "handles an empty array", assertion: "expect(myMap([], (x) => x)).toEqual([])" },
    ],
    hints: ["Build a new result array with a for loop, pushing callback(item, index) each time."],
    solution: `function myMap(array, callback) {\n  const result = [];\n  for (let i = 0; i < array.length; i++) {\n    result.push(callback(array[i], i));\n  }\n  return result;\n}`,
    explanation: "map is 'just' a loop that collects a transformed value per item — implementing it removes the mystery.",
    relatedConcepts: ["map, filter & find", "Loops & iteration"],
  },
  {
    slug: "custom-filter",
    title: "Custom Filter",
    category: "Functions",
    difficulty: "medium",
    skills: ["functions", "arrays"],
    description: "Reimplement Array.prototype.filter as myFilter(array, predicate) without using the built-in .filter.",
    examples: ["myFilter([1,2,3,4], x => x % 2 === 0) → [2,4]"],
    starterCode: `function myFilter(array, predicate) {\n  // your code — do not use array.filter\n}`,
    tests: [
      { description: "keeps only matching elements", assertion: "expect(myFilter([1, 2, 3, 4], (x) => x % 2 === 0)).toEqual([2, 4])" },
      { description: "returns an empty array when nothing matches", assertion: "expect(myFilter([1, 3], (x) => x % 2 === 0)).toEqual([])" },
      { hidden: true, description: "keeps everything when the predicate always matches", assertion: "expect(myFilter([1, 2], () => true)).toEqual([1, 2])" },
    ],
    hints: ["Loop through the array, pushing the item to the result only when predicate(item) is truthy."],
    solution: `function myFilter(array, predicate) {\n  const result = [];\n  for (const item of array) {\n    if (predicate(item)) result.push(item);\n  }\n  return result;\n}`,
    explanation: "filter is a loop with a conditional push — seeing it written out demystifies the built-in version.",
    relatedConcepts: ["map, filter & find", "Custom Map"],
  },
  {
    slug: "custom-reduce",
    title: "Custom Reduce",
    category: "Functions",
    difficulty: "hard",
    skills: ["functions", "arrays"],
    description: "Reimplement Array.prototype.reduce as myReduce(array, reducer, initialValue) without using the built-in .reduce.",
    examples: ["myReduce([1,2,3], (sum, x) => sum + x, 0) → 6"],
    starterCode: `function myReduce(array, reducer, initialValue) {\n  // your code — do not use array.reduce\n}`,
    tests: [
      { description: "sums an array with an initial value", assertion: "expect(myReduce([1, 2, 3], (sum, x) => sum + x, 0)).toBe(6)" },
      { description: "builds a concatenated string", assertion: 'expect(myReduce(["a", "b"], (acc, x) => acc + x, "")).toBe("ab")' },
      { hidden: true, description: "returns the initial value for an empty array", assertion: "expect(myReduce([], (sum, x) => sum + x, 5)).toBe(5)" },
    ],
    hints: ["Start the accumulator at initialValue, then update it by calling reducer(accumulator, item) for each item."],
    solution: `function myReduce(array, reducer, initialValue) {\n  let accumulator = initialValue;\n  for (const item of array) {\n    accumulator = reducer(accumulator, item);\n  }\n  return accumulator;\n}`,
    explanation: "reduce is the most general array method — map and filter can both be expressed in terms of it.",
    relatedConcepts: ["reduce, sort & analysis", "Custom Map", "Custom Filter"],
  },
];
