import type { ChallengeSeed } from "./shared";

export const objects: ChallengeSeed[] = [
  {
    slug: "object-property-counter",
    title: "Object Property Counter",
    category: "Objects",
    difficulty: "easy",
    skills: ["objects"],
    description: "Return the number of own properties on an object.",
    examples: ["countProperties({ a: 1, b: 2 }) → 2"],
    starterCode: `function countProperties(obj) {\n  // your code\n}`,
    tests: [
      { description: "counts a normal object's keys", assertion: "expect(countProperties({ a: 1, b: 2 })).toBe(2)" },
      { description: "counts zero keys on an empty object", assertion: "expect(countProperties({})).toBe(0)" },
      { hidden: true, description: "does not count inherited properties", assertion: "expect(countProperties(Object.create({ inherited: true }))).toBe(0)" },
    ],
    hints: ["Object.keys(obj).length only counts the object's own enumerable properties."],
    solution: `function countProperties(obj) {\n  return Object.keys(obj).length;\n}`,
    explanation: "Object.keys returns only own enumerable keys, correctly excluding anything inherited via the prototype chain.",
    relatedConcepts: ["Objects & methods", "Prototypes & private state"],
  },
  {
    slug: "group-users-by-role",
    title: "Group Users by Role",
    category: "Objects",
    difficulty: "medium",
    skills: ["objects", "arrays"],
    description: "Group an array of users into an object keyed by their role.",
    examples: ['groupByRole([{name:"A",role:"admin"},{name:"B",role:"user"}]) → { admin: [...], user: [...] }'],
    starterCode: `function groupByRole(users) {\n  // your code\n}`,
    tests: [
      {
        description: "groups two roles correctly",
        assertion:
          'expect(groupByRole([{ name: "A", role: "admin" }, { name: "B", role: "user" }, { name: "C", role: "admin" }])).toEqual({ admin: [{ name: "A", role: "admin" }, { name: "C", role: "admin" }], user: [{ name: "B", role: "user" }] })',
      },
      { description: "returns an empty object for an empty list", assertion: "expect(groupByRole([])).toEqual({})" },
      { hidden: true, description: "handles every user sharing one role", assertion: 'expect(groupByRole([{ name: "A", role: "admin" }]).admin).toHaveLength(1)' },
    ],
    hints: ["reduce into an object, pushing each user into the array at groups[user.role], creating it with ??= if missing."],
    solution: `function groupByRole(users) {\n  return users.reduce((groups, user) => {\n    (groups[user.role] ??= []).push(user);\n    return groups;\n  }, {});\n}`,
    explanation: "The ??= operator creates the array for a role the first time it's seen, then every user just pushes onto it.",
    relatedConcepts: ["reduce, sort & analysis", "Objects & methods"],
  },
  {
    slug: "merge-objects",
    title: "Merge Objects",
    category: "Objects",
    difficulty: "easy",
    skills: ["objects"],
    description: "Merge two objects into a new one; properties in the second override the first.",
    examples: ['mergeObjects({a:1,b:2}, {b:3}) → {a:1,b:3}'],
    starterCode: `function mergeObjects(a, b) {\n  // your code\n}`,
    tests: [
      { description: "overrides shared keys with the second object", assertion: "expect(mergeObjects({ a: 1, b: 2 }, { b: 3 })).toEqual({ a: 1, b: 3 })" },
      { description: "combines distinct keys", assertion: "expect(mergeObjects({ a: 1 }, { b: 2 })).toEqual({ a: 1, b: 2 })" },
      { hidden: true, description: "does not mutate either input", assertion: "const x = { a: 1 }; const y = { b: 2 }; mergeObjects(x, y); expect(x).toEqual({ a: 1 })" },
    ],
    hints: ["Spread both objects into a new one, with the second spread last so it wins conflicts."],
    solution: `function mergeObjects(a, b) {\n  return { ...a, ...b };\n}`,
    explanation: "Later spread properties always overwrite earlier ones with the same key.",
    relatedConcepts: ["Spread, rest & immutability"],
  },
  {
    slug: "deep-property-lookup",
    title: "Deep Property Lookup",
    category: "Objects",
    difficulty: "medium",
    skills: ["objects"],
    description: 'Write getPath(obj, "a.b.c") that safely reads a dot-separated nested path, returning undefined if any part is missing.',
    examples: ['getPath({ a: { b: { c: 5 } } }, "a.b.c") → 5', 'getPath({}, "a.b") → undefined'],
    starterCode: `function getPath(obj, path) {\n  // your code\n}`,
    tests: [
      { description: "reads a deeply nested value", assertion: 'expect(getPath({ a: { b: { c: 5 } } }, "a.b.c")).toBe(5)' },
      { description: "returns undefined for a missing path", assertion: 'expect(getPath({}, "a.b")).toBe(undefined)' },
      { hidden: true, description: "reads a top-level value", assertion: 'expect(getPath({ a: 1 }, "a")).toBe(1)' },
    ],
    hints: ["Split the path on '.', then reduce over the segments, using optional chaining at each step."],
    solution: `function getPath(obj, path) {\n  return path.split(".").reduce((value, key) => value?.[key], obj);\n}`,
    explanation: "Optional chaining inside reduce means the moment a segment is missing, every following step short-circuits to undefined.",
    relatedConcepts: ["Nested data", "Optional Chaining"],
  },
  {
    slug: "transform-api-data",
    title: "Transform API Data",
    category: "Objects",
    difficulty: "medium",
    skills: ["objects", "arrays"],
    description: "Given raw API-shaped records { id, first_name, last_name }, return { id, fullName } objects.",
    examples: ['transformUsers([{id:1,first_name:"Ada",last_name:"L"}]) → [{id:1,fullName:"Ada L"}]'],
    starterCode: `function transformUsers(records) {\n  // your code\n}`,
    tests: [
      {
        description: "combines first and last name",
        assertion: 'expect(transformUsers([{ id: 1, first_name: "Ada", last_name: "Lovelace" }])).toEqual([{ id: 1, fullName: "Ada Lovelace" }])',
      },
      { description: "handles multiple records", assertion: 'expect(transformUsers([{ id: 1, first_name: "A", last_name: "B" }, { id: 2, first_name: "C", last_name: "D" }])).toHaveLength(2)' },
      { hidden: true, description: "handles an empty list", assertion: "expect(transformUsers([])).toEqual([])" },
    ],
    hints: ["Map each record to a new object with id and a template-literal-built fullName."],
    solution: `function transformUsers(records) {\n  return records.map((record) => ({\n    id: record.id,\n    fullName: \`${"${record.first_name}"} ${"${record.last_name}"}\`,\n  }));\n}`,
    explanation: "Reshaping snake_case API fields into the camelCase shape your UI expects is one of the most common real transformations.",
    relatedConcepts: ["map, filter & find", "Destructuring"],
  },
  {
    slug: "inventory-calculator",
    title: "Inventory Calculator",
    category: "Objects",
    difficulty: "hard",
    skills: ["objects", "arrays"],
    description: "Given an array of { name, price, quantity } items, return the total inventory value.",
    examples: ['inventoryValue([{name:"Pen",price:2,quantity:3}]) → 6'],
    starterCode: `function inventoryValue(items) {\n  // your code\n}`,
    tests: [
      { description: "values a single item", assertion: 'expect(inventoryValue([{ name: "Pen", price: 2, quantity: 3 }])).toBe(6)' },
      { description: "sums multiple items", assertion: 'expect(inventoryValue([{ name: "Pen", price: 2, quantity: 3 }, { name: "Book", price: 10, quantity: 2 }])).toBe(26)' },
      { hidden: true, description: "values an empty inventory at zero", assertion: "expect(inventoryValue([])).toBe(0)" },
    ],
    hints: ["reduce, summing price * quantity for each item."],
    solution: `function inventoryValue(items) {\n  return items.reduce((total, item) => total + item.price * item.quantity, 0);\n}`,
    explanation: "A realistic aggregation: multiply two fields per record, then fold the results into one total.",
    relatedConcepts: ["reduce, sort & analysis", "Transform API Data"],
  },
];
