import type { Challenge } from "@/types/learning";

const rows = [
  [
    "reverse-a-string",
    "Reverse a String",
    "Strings",
    "easy",
    "Return the supplied text in reverse order.",
    `function reverseString(text) {\n  // your code\n}\nconsole.log(reverseString("hero"));`,
    `if (reverseString("hero") !== "oreh") throw new Error("Expected oreh");\nif (reverseString("") !== "") throw new Error("Empty string failed");`,
    `return text.split("").reverse().join("");`,
  ],
  [
    "fizzbuzz",
    "FizzBuzz",
    "Conditions",
    "easy",
    "Return Fizz, Buzz, FizzBuzz, or the number based on divisibility.",
    `function fizzBuzz(n) {\n  // your code\n}`,
    `if (fizzBuzz(15) !== "FizzBuzz") throw new Error("15 failed");\nif (fizzBuzz(3) !== "Fizz") throw new Error("3 failed");`,
    `return n % 15 === 0 ? "FizzBuzz" : n % 3 === 0 ? "Fizz" : n % 5 === 0 ? "Buzz" : n;`,
  ],
  [
    "find-maximum",
    "Find Maximum",
    "Arrays",
    "easy",
    "Return the largest number without sorting the input.",
    `function findMaximum(numbers) {\n  // your code\n}`,
    `if (findMaximum([4, 9, 2]) !== 9) throw new Error("Expected 9");`,
    `return Math.max(...numbers);`,
  ],
  [
    "count-vowels",
    "Count Vowels",
    "Strings",
    "easy",
    "Count vowels regardless of letter case.",
    `function countVowels(text) {\n  // your code\n}`,
    `if (countVowels("JavaScript") !== 3) throw new Error("Expected 3");`,
    `return (text.match(/[aeiou]/gi) ?? []).length;`,
  ],
  [
    "palindrome",
    "Palindrome Check",
    "Algorithms",
    "medium",
    "Ignore case and non-alphanumeric characters, then detect a palindrome.",
    `function isPalindrome(text) {\n  // your code\n}`,
    `if (!isPalindrome("Never odd or even")) throw new Error("Phrase failed");`,
    `const clean = text.toLowerCase().replace(/[^a-z0-9]/g, "");\nreturn clean === [...clean].reverse().join("");`,
  ],
  [
    "remove-duplicates",
    "Remove Duplicates",
    "Arrays",
    "easy",
    "Return a new array containing each value once.",
    `function unique(values) {\n  // your code\n}`,
    `if (JSON.stringify(unique([1,1,2])) !== "[1,2]") throw new Error("Duplicates remain");`,
    `return [...new Set(values)];`,
  ],
  [
    "flatten-array",
    "Flatten an Array",
    "Arrays",
    "medium",
    "Flatten an arbitrarily nested array without mutating it.",
    `function flatten(values) {\n  // your code\n}`,
    `if (JSON.stringify(flatten([1,[2,[3]]])) !== "[1,2,3]") throw new Error("Nested input failed");`,
    `return values.flat(Infinity);`,
  ],
  [
    "group-objects",
    "Group Objects",
    "Objects",
    "medium",
    "Group records by a supplied property.",
    `function groupBy(items, key) {\n  // your code\n}`,
    `const out = groupBy([{t:"a"},{t:"b"},{t:"a"}], "t");\nif (out.a.length !== 2) throw new Error("Grouping failed");`,
    `return items.reduce((groups, item) => {\n  (groups[item[key]] ??= []).push(item);\n  return groups;\n}, {});`,
  ],
  [
    "debug-total",
    "Repair the Total",
    "Debugging",
    "easy",
    "Fix the misspelled identifiers so the function returns a total.",
    `function calculateTotal(price, quantity) {\n  const total = price * quantiy;\n  return totals;\n}`,
    `if (calculateTotal(8, 3) !== 24) throw new Error("Expected 24");`,
    `function calculateTotal(price, quantity) {\n  const total = price * quantity;\n  return total;\n}`,
  ],
  [
    "memoize",
    "Implement Memoize",
    "Functions",
    "hard",
    "Cache results by arguments so repeated calls avoid repeated work.",
    `function memoize(fn) {\n  // your code\n}`,
    `let calls=0; const twice=memoize(n=>{calls++; return n*2}); twice(2); twice(2); if(calls!==1) throw new Error("Not cached");`,
    `const cache = new Map();\nreturn (...args) => { const key = JSON.stringify(args); if (!cache.has(key)) cache.set(key, fn(...args)); return cache.get(key); };`,
  ],
  [
    "debounce",
    "Implement Debounce",
    "Functions",
    "hard",
    "Return a wrapper that delays execution until calls have stopped.",
    `function debounce(fn, delay) {\n  // your code\n}`,
    `if (typeof debounce(() => {}, 10) !== "function") throw new Error("Expected a function");`,
    `let timer;\nreturn (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); };`,
  ],
  [
    "concurrent-apis",
    "Fetch Concurrent APIs",
    "Async",
    "hard",
    "Resolve independent requests concurrently and preserve result order.",
    `async function loadAll(urls) {\n  // your code\n}`,
    `if (typeof loadAll(["/a"])?.then !== "function") throw new Error("Expected a Promise");`,
    `return Promise.all(urls.map(async url => { const response = await fetch(url); if (!response.ok) throw new Error(\`Failed: ${"${url}"}\`); return response.json(); }));`,
  ],
] as const;

export const challenges: Challenge[] = rows.map(
  ([
    slug,
    title,
    category,
    difficulty,
    description,
    starterCode,
    testCode,
    solution,
  ]) => ({
    slug,
    title,
    category,
    difficulty,
    description,
    starterCode,
    testCode,
    solution,
    examples: [
      `Input and output depend on the function contract described above.`,
    ],
    hint: "Start with the smallest input. State the expected output before writing the transformation.",
    explanation:
      "The reference solution favors a small, explicit transformation and keeps the caller-facing contract predictable.",
  }),
);
