import type { InterviewQuestion } from "@/types/learning";

type Seed = InterviewQuestion;

export const interviewQuestions: Seed[] = [
  // ---------------------------------------------------------------- Fundamentals
  {
    slug: "var-let-const",
    question: "What is the difference between var, let, and const?",
    category: "Fundamentals",
    difficulty: "easy",
    shortAnswer: "var is function-scoped and hoisted with a default of undefined; let and const are block-scoped and live in the temporal dead zone until initialized; const additionally forbids reassignment.",
    deepExplanation: "var declarations attach to the nearest function (or global scope), ignoring block boundaries like if/for, and are hoisted with an initial value of undefined. let and const are scoped to the nearest block ({}) and are hoisted into a 'temporal dead zone' where accessing them before their declaration line throws instead of returning undefined. const additionally disallows reassigning the binding (though the value it points to, if an object, can still be mutated).",
    codeExample: `if (true) {\n  var x = 1;\n  let y = 2;\n}\nconsole.log(x); // 1 — leaked out of the block\nconsole.log(typeof y); // ReferenceError if uncommented`,
    commonWrongAnswer: "\"They're all basically the same, just newer syntax.\" — this misses the scoping and reassignment differences entirely.",
    interviewTrap: "Interviewers often ask you to predict console output involving var inside a loop with a closure — the function-scoping of var (not let) is exactly what causes the classic 'all callbacks log the same value' bug.",
    followUp: "Why does const not make an object immutable, and how would you actually freeze one?",
  },
  {
    slug: "double-equals-triple-equals",
    question: "What is the difference between == and ===?",
    category: "Fundamentals",
    difficulty: "easy",
    shortAnswer: "== compares after coercing both operands to a common type; === compares type and value with no coercion.",
    deepExplanation: "== applies a set of coercion rules (defined in the spec's Abstract Equality Comparison) before comparing, which can produce surprising results like '' == 0 being true. === (Strict Equality Comparison) short-circuits to false immediately if the types differ, making it predictable and the recommended default.",
    codeExample: `console.log(0 == "0");   // true\nconsole.log(0 === "0");  // false\nconsole.log(null == undefined);  // true\nconsole.log(null === undefined); // false`,
    commonWrongAnswer: "\"== checks value and === checks value and reference.\" — reference equality isn't the distinction; coercion is.",
    interviewTrap: "Be ready to explain WHY '' == 0 and '0' == false are both true — it tests whether you actually know the coercion rules or just memorized 'use ==='.",
    followUp: "What are the exact six falsy values in JavaScript?",
  },
  {
    slug: "what-is-hoisting",
    question: "What is hoisting?",
    category: "Fundamentals",
    difficulty: "medium",
    shortAnswer: "Hoisting is the engine's behavior of registering variable and function declarations during a setup phase before executing code top to bottom.",
    deepExplanation: "Function declarations are hoisted completely — both the name and the implementation — so they're callable before their line in the file. var declarations are hoisted with their name only, initialized to undefined. let and const are hoisted too, but remain uninitialized in the temporal dead zone until their declaration executes, throwing a ReferenceError if accessed earlier.",
    codeExample: `console.log(a); // undefined\nvar a = 5;\n\nconsole.log(sayHi()); // works — function declarations hoist fully\nfunction sayHi() { return "hi"; }`,
    commonWrongAnswer: "\"Hoisting moves your code to the top of the file.\" — nothing physically moves; only the declaration's registration happens early, not the assignment.",
    interviewTrap: "Interviewers ask you to predict output for a var referenced before assignment vs a let in the same position — the first logs undefined, the second throws.",
    followUp: "What exactly is the temporal dead zone, and why does it exist?",
  },
  {
    slug: "null-vs-undefined",
    question: "What is the difference between null and undefined?",
    category: "Fundamentals",
    difficulty: "easy",
    shortAnswer: "undefined means a variable has been declared but never assigned a value; null is an explicit, intentional assignment representing 'no value'.",
    deepExplanation: "undefined is the default value JavaScript gives to an uninitialized variable, a missing function argument, or a missing object property. null is a value developers assign deliberately to signal 'this is empty on purpose'. They are loosely equal (null == undefined) but not strictly equal, and typeof null famously returns 'object' due to a decades-old bug kept for compatibility.",
    codeExample: `let a;\nconsole.log(a);        // undefined\nlet b = null;\nconsole.log(b);        // null\nconsole.log(typeof a); // "undefined"\nconsole.log(typeof b); // "object"`,
    commonWrongAnswer: "\"They're interchangeable.\" — using them interchangeably in an API's contract (e.g. sometimes null, sometimes undefined for 'missing') is a real source of bugs.",
    interviewTrap: "Asking why typeof null === 'object' checks whether you know this is a language quirk, not a meaningful type signal — you should still use === null to check for it explicitly.",
    followUp: "How would you check whether a value is 'nullish' (either null or undefined) in one expression?",
  },
  {
    slug: "typeof-quirks",
    question: "What are some surprising results of the typeof operator?",
    category: "Fundamentals",
    difficulty: "medium",
    shortAnswer: "typeof null is \"object\", and typeof for a function is \"function\" even though functions are technically objects.",
    deepExplanation: "typeof null returning 'object' is a bug from JavaScript's original 1995 implementation, preserved for backward compatibility. Functions get their own 'function' result from typeof as a convenience, even though Array.isArray/instanceof show that functions are indeed a kind of object under the hood.",
    codeExample: `typeof null;          // "object"\ntypeof function(){};  // "function"\ntypeof [];             // "object"\ntypeof undefined;      // "undefined"`,
    commonWrongAnswer: "\"typeof always tells you the real, complete type.\" — it doesn't distinguish arrays from plain objects, for instance.",
    interviewTrap: "If asked to detect an array, typeof won't help (it says 'object' for both) — Array.isArray() is the correct tool, a common gotcha.",
    followUp: "How would you reliably check if a value is an array versus a plain object?",
  },

  // ---------------------------------------------------------------- Functions
  {
    slug: "function-declaration-vs-expression",
    question: "What is the difference between a function declaration and a function expression?",
    category: "Functions",
    difficulty: "easy",
    shortAnswer: "A function declaration is hoisted fully and callable before its line; a function expression is only usable after the line where it's assigned.",
    deepExplanation: "`function foo() {}` is a declaration — the entire function is registered during hoisting. `const foo = function () {}` (or an arrow function) is an expression assigned to a variable, and that variable follows normal let/const/var rules — so calling it before the assignment line throws or returns undefined depending on the declaration keyword used for the variable.",
    codeExample: `sayHi(); // works\nfunction sayHi() { return "hi"; }\n\nsayBye(); // TypeError: sayBye is not a function\nvar sayBye = function () { return "bye"; };`,
    commonWrongAnswer: "\"They behave identically, just different syntax.\" — the hoisting difference is significant in practice.",
    interviewTrap: "Predicting the exact error type (TypeError vs ReferenceError) when calling a var-assigned function expression too early trips up many candidates.",
    followUp: "How does this change if the function expression is assigned to a `let` instead of `var`?",
  },
  {
    slug: "default-parameters",
    question: "How do default parameters work in JavaScript, and when are they applied?",
    category: "Functions",
    difficulty: "easy",
    shortAnswer: "A default parameter value is used only when the argument is undefined — not for any other falsy value like null, 0, or an empty string.",
    deepExplanation: "Default parameters are evaluated at call time, left to right, and can even reference earlier parameters. They only kick in when the corresponding argument is strictly undefined (including simply omitting it) — passing null explicitly does NOT trigger the default, which surprises people expecting 'falsy triggers default'.",
    codeExample: `function greet(name = "Guest") {\n  return \`Hi, ${"${name}"}\`;\n}\ngreet();      // "Hi, Guest"\ngreet(undefined); // "Hi, Guest"\ngreet(null);  // "Hi, null" — default NOT applied`,
    commonWrongAnswer: "\"Default parameters apply whenever the argument is falsy.\" — they only apply for undefined specifically.",
    interviewTrap: "Ask what greet(null) logs — many candidates confidently say 'Hi, Guest', which is wrong.",
    followUp: "How would you write a default that also treats null as 'use the default'?",
  },
  {
    slug: "rest-vs-arguments",
    question: "What is the difference between rest parameters and the arguments object?",
    category: "Functions",
    difficulty: "medium",
    shortAnswer: "Rest parameters (...args) produce a real Array with all array methods; arguments is an array-like object available only in regular functions, without map/filter/reduce built in.",
    deepExplanation: "The arguments object exists in every regular (non-arrow) function and reflects all passed arguments, but it isn't a true Array — you'd need Array.from(arguments) to use array methods on it. Rest parameters are actual arrays, are the modern preferred approach, and are the ONLY option inside arrow functions, since arrow functions have no arguments object of their own (they inherit it from an enclosing regular function, if any).",
    codeExample: `function sumOld() {\n  return Array.from(arguments).reduce((a, b) => a + b, 0);\n}\nfunction sumNew(...nums) {\n  return nums.reduce((a, b) => a + b, 0);\n}`,
    commonWrongAnswer: "\"arguments and rest parameters are interchangeable in every function.\" — arrow functions have no arguments object at all.",
    interviewTrap: "Ask what `arguments` refers to inside an arrow function nested in a regular function — it's the outer regular function's arguments, not the arrow's own.",
    followUp: "Why don't arrow functions have their own `arguments` object?",
  },
  {
    slug: "pure-functions",
    question: "What makes a function 'pure', and why does it matter?",
    category: "Functions",
    difficulty: "medium",
    shortAnswer: "A pure function's output depends only on its inputs, and it causes no observable side effects outside its own scope.",
    deepExplanation: "Purity means calling a function twice with the same arguments always returns the same result, and the function does not mutate external state, perform I/O, or depend on anything besides its parameters. Pure functions are trivial to test, safely memoizable, and safe to run in any order — properties impure functions cannot guarantee.",
    codeExample: `// Impure: depends on and mutates outside state\nlet total = 0;\nfunction addImpure(n) { total += n; return total; }\n\n// Pure: only depends on its arguments\nfunction addPure(total, n) { return total + n; }`,
    commonWrongAnswer: "\"Pure just means it doesn't use console.log.\" — logging is one example of a side effect, but purity is broader (no mutation, no I/O, no randomness, no reading external mutable state).",
    interviewTrap: "Candidates often say a function using Math.random() or Date.now() internally is pure — it isn't, since its output isn't determined solely by its arguments.",
    followUp: "Can a pure function still throw an error? Does that break purity?",
  },

  // ---------------------------------------------------------------- Scope
  {
    slug: "lexical-scope",
    question: "What is lexical scope?",
    category: "Scope",
    difficulty: "medium",
    shortAnswer: "Lexical scope means a variable's accessibility is determined by where it is physically written in the source code, not by how or where the function is called.",
    deepExplanation: "When a function is defined, it captures a reference to the scope it was written inside — its enclosing function(s) and the global scope — and that chain is fixed at write-time, regardless of the call site. This is what makes closures possible: an inner function can always see variables from every scope literally surrounding it in the source.",
    codeExample: `function outer() {\n  const secret = 42;\n  function inner() {\n    return secret; // resolved lexically, from where inner is WRITTEN\n  }\n  return inner();\n}\nconsole.log(outer()); // 42`,
    commonWrongAnswer: "\"Scope depends on which function called it.\" — that describes dynamic scoping, which JavaScript does not use (except for `this`, which is a separate mechanism).",
    interviewTrap: "Don't confuse lexical scope (variable lookup) with `this` binding (which IS dynamic, based on the call site) — interviewers love probing this exact distinction.",
    followUp: "Given that `this` is dynamic but variable scope is lexical, how do arrow functions bridge that gap?",
  },
  {
    slug: "block-scope",
    question: "What is block scope, and how did let/const change JavaScript's scoping model?",
    category: "Scope",
    difficulty: "easy",
    shortAnswer: "Block scope confines a variable's visibility to the nearest enclosing {} — let and const introduced this, whereas var ignores blocks entirely.",
    deepExplanation: "Before ES6, var was the only option and only respected function boundaries, so a variable declared inside an if or for block was still visible throughout the whole function. let and const fixed this by scoping to the nearest block, matching the behavior most other languages already had, and reducing an entire category of accidental variable leakage bugs.",
    codeExample: `for (let i = 0; i < 3; i++) {}\nconsole.log(typeof i); // "undefined" — i doesn't exist out here\n\nfor (var j = 0; j < 3; j++) {}\nconsole.log(j); // 3 — leaked out of the loop`,
    commonWrongAnswer: "\"Block scope and function scope are the same thing.\" — they're meaningfully different, especially inside if/for/while blocks.",
    interviewTrap: "Predicting whether a variable is accessible right after a for loop is a very common quick-check question distinguishing var from let.",
    followUp: "Why does using let in a for loop give each iteration its own independent binding?",
  },
  {
    slug: "global-scope-pollution",
    question: "What is global scope pollution, and how do modules help avoid it?",
    category: "Scope",
    difficulty: "medium",
    shortAnswer: "Global pollution happens when too many variables/functions are attached to the global object, risking name collisions between unrelated scripts.",
    deepExplanation: "Before ES modules, every top-level var/function in a plain script became a property of the global object (window in browsers), so two independently-authored scripts using the same variable name could silently overwrite each other. ES modules (and even the older IIFE pattern) fix this by giving each file its own scope — nothing is global unless deliberately exported.",
    codeExample: `// old-school script.js (no modules)\nvar count = 0; // becomes window.count\n\n// module.js\nexport const count = 0; // stays local to this module`,
    commonWrongAnswer: "\"Global variables are just a style preference.\" — they're a real source of production bugs in any codebase with multiple contributors or third-party scripts.",
    interviewTrap: "Interviewers may ask why an IIFE `(function () { ... })()` was a common pre-ES6 pattern — it's precisely to avoid leaking to the global scope.",
    followUp: "How do ES module imports/exports differ from CommonJS require/module.exports in terms of scope?",
  },
  {
    slug: "temporal-dead-zone",
    question: "What is the temporal dead zone (TDZ)?",
    category: "Scope",
    difficulty: "hard",
    shortAnswer: "The TDZ is the span from the start of a block to a let/const declaration's actual line, during which accessing that variable throws a ReferenceError.",
    deepExplanation: "let and const are hoisted (the engine knows they exist), but unlike var they are not initialized to undefined during hoisting — they stay in an uninitialized state. Any access before the declaration's line executes throws, which is a deliberate design choice that catches use-before-definition bugs var could never catch.",
    codeExample: `{\n  console.log(value); // ReferenceError, not undefined\n  let value = 10;\n}`,
    commonWrongAnswer: "\"let and const aren't hoisted at all.\" — they are hoisted, just left uninitialized instead of defaulted to undefined like var.",
    interviewTrap: "Interviewers ask you to contrast the TDZ error (ReferenceError) with what the equivalent var code would produce (undefined, no error) — know both outcomes precisely.",
    followUp: "Does the TDZ apply to function parameters with default values referencing later parameters?",
  },

  // ---------------------------------------------------------------- Arrays
  {
    slug: "map-vs-foreach",
    question: "What is the difference between map and forEach?",
    category: "Arrays",
    difficulty: "easy",
    shortAnswer: "map returns a new array built from the callback's return values; forEach returns undefined and is used purely for side effects.",
    deepExplanation: "Both iterate every element, but map collects each callback's return value into a brand-new array of the same length, making it ideal for transformations. forEach always returns undefined regardless of what the callback returns, signaling that its purpose is running side effects (like logging), not building a new collection.",
    codeExample: `const doubled = [1, 2, 3].map(n => n * 2); // [2, 4, 6]\nconst result = [1, 2, 3].forEach(n => n * 2); // undefined`,
    commonWrongAnswer: "\"They're the same, just map is newer.\" — using map when you don't need its return value (or forEach when you do) is a common code-smell interviewers watch for.",
    interviewTrap: "A candidate writing `const doubled = arr.forEach(n => n * 2)` and expecting doubled to be an array is a real, common mistake worth flagging.",
    followUp: "When would you deliberately choose forEach over a for...of loop?",
  },
  {
    slug: "splice-vs-slice",
    question: "What is the difference between splice and slice?",
    category: "Arrays",
    difficulty: "easy",
    shortAnswer: "slice returns a shallow copy of a portion of the array without modifying the original; splice mutates the original array by removing/inserting elements in place.",
    deepExplanation: "slice(start, end) is non-destructive and commonly used to safely copy or extract part of an array. splice(start, deleteCount, ...items) mutates the array directly, removing `deleteCount` elements starting at `start` and optionally inserting new items there, returning the removed elements (not the modified array).",
    codeExample: `const arr = [1, 2, 3, 4];\nconst copy = arr.slice(1, 3);   // [2, 3]; arr unchanged\nconst removed = arr.splice(1, 2); // removed = [2, 3]; arr is now [1, 4]`,
    commonWrongAnswer: "\"splice returns the modified array.\" — it returns the removed elements, not the array itself.",
    interviewTrap: "Ask what splice() returns specifically — most candidates assume it's the mutated array rather than the removed items.",
    followUp: "Why might mutating methods like splice be risky to use directly on state in a React application?",
  },
  {
    slug: "array-vs-array-like",
    question: "What is an 'array-like' object, and how do you convert one to a real array?",
    category: "Arrays",
    difficulty: "medium",
    shortAnswer: "An array-like object has indexed properties and a length, but lacks array methods like map/filter — NodeList and `arguments` are common examples.",
    deepExplanation: "Array-like objects satisfy the shape of an array (numeric keys, a length property) but don't inherit from Array.prototype, so calling .map() directly on one throws. Array.from() or the spread operator (when the object is iterable) both convert them into genuine arrays with full method support.",
    codeExample: `function example() {\n  // arguments is array-like, not a real array\n  const real = Array.from(arguments);\n  return real.map((x) => x * 2);\n}`,
    commonWrongAnswer: "\"Anything with a length property is an array.\" — plenty of non-array objects have a length property (like strings) without being arrays.",
    interviewTrap: "document.querySelectorAll returns a NodeList (array-like but iterable) — calling .map directly on it throws in some environments, a real gotcha worth knowing.",
    followUp: "Is a NodeList from querySelectorAll iterable with for...of even though it's not an array?",
  },
  {
    slug: "flat-flatmap",
    question: "What do flat() and flatMap() do?",
    category: "Arrays",
    difficulty: "medium",
    shortAnswer: "flat(depth) flattens nested arrays up to the given depth; flatMap() maps each element then flattens the result by exactly one level, in one pass.",
    deepExplanation: "flat() takes an optional depth argument (default 1, or Infinity for full flattening) and returns a new, flattened array. flatMap() is equivalent to calling .map() followed by .flat(1), but does it more efficiently in a single traversal — useful when a mapping callback might return zero, one, or many items per input element.",
    codeExample: `[1, [2, [3]]].flat();       // [1, 2, [3]]\n[1, [2, [3]]].flat(Infinity); // [1, 2, 3]\n[1, 2, 3].flatMap(n => [n, n * 2]); // [1, 2, 2, 4, 3, 6]`,
    commonWrongAnswer: "\"flatMap is just map with a fancier name.\" — the automatic one-level flatten is the entire point of flatMap.",
    interviewTrap: "Ask how you'd implement a function that both filters and maps in one pass — flatMap returning [] to 'skip' an element is an elegant, non-obvious answer.",
    followUp: "How would you use flatMap to implement a filter-and-map in a single array pass?",
  },

  // ---------------------------------------------------------------- Objects
  {
    slug: "shallow-vs-deep-copy",
    question: "What is the difference between a shallow copy and a deep copy?",
    category: "Objects",
    difficulty: "medium",
    shortAnswer: "A shallow copy duplicates only the top level of an object — nested objects are still shared by reference; a deep copy recursively duplicates every nested level too.",
    deepExplanation: "Spread ({ ...obj }) and Object.assign() both create shallow copies: primitive top-level properties are genuinely copied, but any nested object or array is copied by reference, so mutating a nested value through the copy also affects the original. structuredClone(obj) (or a manual recursive clone / JSON round-trip for simple data) produces a true deep copy with no shared references at any level.",
    codeExample: `const original = { user: { name: "Ada" } };\nconst shallow = { ...original };\nshallow.user.name = "Grace";\nconsole.log(original.user.name); // "Grace" — shared reference\n\nconst deep = structuredClone(original);\ndeep.user.name = "Bo";\nconsole.log(original.user.name); // still "Grace"`,
    commonWrongAnswer: "\"Spread always makes a completely independent copy.\" — only true for objects with exclusively primitive values.",
    interviewTrap: "A candidate confidently using spread to 'safely' copy a deeply nested state object is a very common real bug interviewers probe for.",
    followUp: "What are the limitations of using JSON.parse(JSON.stringify(obj)) as a deep clone technique?",
  },
  {
    slug: "object-freeze",
    question: "What does Object.freeze() do, and what are its limitations?",
    category: "Objects",
    difficulty: "medium",
    shortAnswer: "Object.freeze() prevents adding, removing, or reassigning an object's own top-level properties, but it is shallow — nested objects remain mutable.",
    deepExplanation: "A frozen object throws (in strict mode) or silently fails (non-strict) on attempts to add, delete, or reassign its direct properties. However, freeze() only affects one level deep — a property that itself holds an object can still be mutated freely unless that nested object is separately frozen too.",
    codeExample: `const settings = Object.freeze({ theme: "dark", nested: { on: true } });\nsettings.theme = "light";       // silently fails\nsettings.nested.on = false;     // succeeds! nested isn't frozen\nconsole.log(settings.nested.on); // false`,
    commonWrongAnswer: "\"Object.freeze makes an object fully immutable.\" — only true for a flat object with no nested objects.",
    interviewTrap: "Ask what happens when you mutate a nested property of a frozen object — many assume it throws or fails, but it silently succeeds.",
    followUp: "How would you deeply freeze an object recursively?",
  },
  {
    slug: "computed-property-names",
    question: "What are computed property names in object literals?",
    category: "Objects",
    difficulty: "easy",
    shortAnswer: "Computed property names let you use a dynamic expression, wrapped in [], as an object key at creation time.",
    deepExplanation: "Before ES6, creating an object with a dynamic key required creating the object first, then assigning obj[key] = value on a separate line. Computed property names let you do this inline within the object literal itself using square brackets around any expression.",
    codeExample: `const key = "role";\nconst user = {\n  name: "Ada",\n  [key]: "admin",\n  [\`${"${key}"}Level\`]: 3,\n};\nconsole.log(user); // { name: "Ada", role: "admin", roleLevel: 3 }`,
    commonWrongAnswer: "\"You can only use string literals as object keys.\" — any expression, including function calls, can be used inside the brackets.",
    interviewTrap: "Ask how you'd build an object where the key comes from a variable, without a separate assignment line afterward — a good chance to show this feature.",
    followUp: "Can computed property names be used with class fields as well?",
  },
  {
    slug: "property-descriptors",
    question: "What is a property descriptor, and what does Object.defineProperty enable?",
    category: "Objects",
    difficulty: "hard",
    shortAnswer: "A property descriptor controls a property's writability, enumerability, and configurability — Object.defineProperty lets you set these explicitly, including defining getters/setters.",
    deepExplanation: "Every object property has hidden metadata: whether it can be reassigned (writable), whether it shows up in for...in/Object.keys (enumerable), and whether it can be deleted or reconfigured (configurable). Object.defineProperty gives fine-grained control over these, and can also define accessor properties (get/set) that compute a value dynamically rather than storing it directly.",
    codeExample: `const user = {};\nObject.defineProperty(user, "id", {\n  value: 1,\n  writable: false,\n  enumerable: false,\n});\nuser.id = 99;\nconsole.log(user.id); // 1 — silently unchanged\nconsole.log(Object.keys(user)); // [] — hidden from enumeration`,
    commonWrongAnswer: "\"All object properties behave identically.\" — normal property assignment (obj.x = 1) always creates a writable, enumerable, configurable property by default, unlike explicitly defined ones.",
    interviewTrap: "This is how libraries implement 'hidden' internal properties that don't show up in JSON.stringify or Object.keys — a nuance many candidates have never encountered.",
    followUp: "How does Vue 2's reactivity system use property descriptors (getters/setters) under the hood?",
  },

  // ---------------------------------------------------------------- DOM
  {
    slug: "bubbling-vs-capturing",
    question: "What is the difference between event bubbling and event capturing?",
    category: "DOM",
    difficulty: "medium",
    shortAnswer: "Capturing fires listeners from the outermost ancestor down to the target; bubbling fires them from the target back up to the outermost ancestor — bubbling is the default.",
    deepExplanation: "When an event occurs, the browser runs it through three phases: capture (root to target), target, and bubble (target back to root). addEventListener's third argument (or { capture: true }) opts a listener into the capture phase; by default, listeners run during the bubble phase, which is why delegation patterns rely on bubbling.",
    codeExample: `parent.addEventListener("click", () => console.log("bubble: parent"));\nparent.addEventListener("click", () => console.log("capture: parent"), true);\nchild.addEventListener("click", () => console.log("target: child"));\n// clicking child logs: capture: parent, target: child, bubble: parent`,
    commonWrongAnswer: "\"Capturing and bubbling always both happen and you can't choose.\" — both phases occur for every event, but which phase YOUR listener responds to depends on the third argument.",
    interviewTrap: "Ask candidates to order the console.logs from a capture-phase parent listener, a target-phase child listener, and a bubble-phase parent listener.",
    followUp: "How does stopPropagation() interact with these two phases?",
  },
  {
    slug: "event-delegation-interview",
    question: "What is event delegation, and why is it useful?",
    category: "DOM",
    difficulty: "medium",
    shortAnswer: "Event delegation attaches a single listener to a shared ancestor instead of one listener per child, relying on bubbling and checking event.target to identify which child triggered it.",
    deepExplanation: "Because events bubble up through ancestors, a parent element's single listener can inspect event.target (or event.target.closest(selector)) to determine the actual originating child, including children added to the DOM after the listener was attached. This dramatically reduces memory usage for long lists and removes the need to re-bind listeners when the list changes.",
    codeExample: `list.addEventListener("click", (event) => {\n  const item = event.target.closest("li");\n  if (item) console.log("clicked", item.dataset.id);\n});`,
    commonWrongAnswer: "\"Delegation means the event fires on every ancestor separately.\" — it's one listener reasoning about where the event originated, not multiple firings.",
    interviewTrap: "Ask how delegation handles elements added to the list after the listener was attached — this is exactly the scenario where per-child listeners would fail silently.",
    followUp: "What's a downside or edge case of relying heavily on event delegation?",
  },
  {
    slug: "reflow-repaint",
    question: "What is the difference between a browser reflow and a repaint?",
    category: "DOM",
    difficulty: "hard",
    shortAnswer: "A reflow recalculates layout (size and position of elements); a repaint redraws pixels without changing layout — reflows are more expensive and often trigger a subsequent repaint.",
    deepExplanation: "Changing something that affects geometry (width, adding/removing an element, changing text content) forces the browser to recompute the layout tree (reflow), which then requires repainting the affected pixels. Changing only visual properties that don't affect layout (like background-color or visibility: hidden vs display: none) triggers a repaint without a reflow, which is comparatively cheap.",
    codeExample: `// Triggers layout thrashing: reading then writing repeatedly forces\n// multiple synchronous reflows in a loop\nelements.forEach((el) => {\n  const height = el.offsetHeight; // read (forces reflow if layout is dirty)\n  el.style.height = height + 10 + "px"; // write\n});`,
    commonWrongAnswer: "\"Reflow and repaint are the same thing, just different browser vendor terms.\" — they are genuinely distinct, sequential steps in the rendering pipeline.",
    interviewTrap: "Ask how to avoid 'layout thrashing' when reading and writing to the DOM in a loop — batching reads separately from writes is the expected answer.",
    followUp: "How does using CSS transform instead of top/left for animation avoid triggering reflow?",
  },
  {
    slug: "queryselector-vs-getelementbyid",
    question: "What is the difference between querySelector and getElementById?",
    category: "DOM",
    difficulty: "easy",
    shortAnswer: "getElementById looks up one element by its exact id (fast, id-only); querySelector accepts any CSS selector and returns the first match (more flexible, slightly slower).",
    deepExplanation: "getElementById is a narrow, highly optimized lookup limited to the id attribute. querySelector (and querySelectorAll for all matches) accepts the full power of CSS selectors — classes, attributes, combinators — making it far more versatile at the cost of a marginally slower lookup in most engines.",
    codeExample: `document.getElementById("save-button");\ndocument.querySelector("#save-button");        // equivalent for an id\ndocument.querySelector(".card:first-child");    // impossible with getElementById`,
    commonWrongAnswer: "\"querySelector always replaces getElementById with no tradeoffs.\" — for a simple id lookup in a hot path, getElementById is a touch faster and communicates intent clearly.",
    interviewTrap: "Ask what querySelectorAll returns (a static NodeList, not a live collection) versus getElementsByClassName (a live HTMLCollection) — a frequent follow-up trap.",
    followUp: "What does it mean for an HTMLCollection to be 'live', and why can that cause bugs in a loop?",
  },

  // ---------------------------------------------------------------- Async
  {
    slug: "promise-vs-callback",
    question: "What problems do Promises solve compared to plain callbacks?",
    category: "Async",
    difficulty: "medium",
    shortAnswer: "Promises flatten deeply nested callback pyramids into readable chains, provide built-in error propagation via .catch(), and guarantee a callback fires exactly once.",
    deepExplanation: "Callback-based async code sequencing multiple steps nests one callback inside another ('callback hell'), and error handling has to be manually repeated at every level. Promises represent a future value as a first-class object that can be chained flatly with .then(), propagate errors down the chain automatically until caught, and are guaranteed to settle (fulfill or reject) exactly once, unlike a callback which could technically be invoked multiple times or never.",
    codeExample: `// callback pyramid\ngetUser(id, (user) => {\n  getPosts(user.id, (posts) => {\n    getComments(posts[0].id, (comments) => { /* ... */ });\n  });\n});\n\n// promise chain\ngetUser(id)\n  .then((user) => getPosts(user.id))\n  .then((posts) => getComments(posts[0].id))\n  .catch((error) => console.error(error));`,
    commonWrongAnswer: "\"Promises make async code synchronous.\" — the code still runs asynchronously; Promises only make sequencing and error handling easier to read.",
    interviewTrap: "Ask what happens if you forget a .catch() — the rejection becomes an 'unhandled promise rejection', not a silent no-op.",
    followUp: "How does async/await relate to Promises under the hood?",
  },
  {
    slug: "async-await-vs-then",
    question: "What is the difference between async/await and .then() chaining?",
    category: "Async",
    difficulty: "medium",
    shortAnswer: "They're two syntaxes over the same Promise mechanism — async/await lets asynchronous code read like synchronous, top-to-bottom code, while .then() is explicit chaining.",
    deepExplanation: "An async function always returns a Promise, and `await` pauses execution inside that function until the awaited Promise settles, unwrapping its value directly into a variable. This avoids the visual nesting of long .then() chains, especially when a later step depends on multiple earlier awaited values, but requires wrapping code in try/catch for error handling instead of a trailing .catch().",
    codeExample: `// .then chaining\nfunction load() {\n  return getUser().then((user) => getPosts(user.id));\n}\n\n// async/await, equivalent behavior\nasync function load() {\n  const user = await getUser();\n  return getPosts(user.id);\n}`,
    commonWrongAnswer: "\"async/await is faster than Promises.\" — there's no performance difference; it's purely syntactic sugar over the same Promise machinery.",
    interviewTrap: "Ask how error handling changes between the two styles — forgetting try/catch around an await is functionally the same as forgetting .catch(), just a different-looking bug.",
    followUp: "What happens if you forget the `async` keyword but still try to use `await` inside a function?",
  },
  {
    slug: "promise-all-vs-allsettled",
    question: "What is the difference between Promise.all and Promise.allSettled?",
    category: "Async",
    difficulty: "medium",
    shortAnswer: "Promise.all rejects immediately if any input rejects; Promise.allSettled always waits for every promise and reports each one's individual outcome (fulfilled or rejected).",
    deepExplanation: "Promise.all is 'all or nothing' — perfect when every operation must succeed for the result to be meaningful. Promise.allSettled never short-circuits; it resolves once every promise has settled, returning an array of { status, value } or { status, reason } objects, which is ideal when you want partial results even if some requests fail.",
    codeExample: `const results = await Promise.allSettled([\n  fetch("/a"), fetch("/b-that-fails"),\n]);\n// [{status:"fulfilled",value:...}, {status:"rejected",reason:...}]`,
    commonWrongAnswer: "\"allSettled is just a safer version of all that you should always use instead.\" — Promise.all's fail-fast behavior is exactly correct when partial success is meaningless.",
    interviewTrap: "Ask what Promise.all returns if one of five inputs rejects immediately — it rejects right away with that single reason, discarding the other four results even if they'd have succeeded.",
    followUp: "How would you implement retry logic for just the failed promises from an allSettled result?",
  },
  {
    slug: "async-race-conditions",
    question: "What is a race condition in asynchronous JavaScript, and how can you avoid one?",
    category: "Async",
    difficulty: "hard",
    shortAnswer: "A race condition happens when multiple async operations can finish in an unpredictable order and the code assumes a specific one, leading to stale or incorrect results.",
    deepExplanation: "A classic example is a search-as-you-type feature: if a fast response to an old query arrives after a slow response to a newer query, the UI can display outdated results. Fixes include tracking a request id/token and ignoring stale responses, using AbortController to cancel outdated requests, or debouncing input so fewer requests are in flight simultaneously.",
    codeExample: `let latestRequestId = 0;\nasync function search(query) {\n  const requestId = ++latestRequestId;\n  const results = await fetchResults(query);\n  if (requestId !== latestRequestId) return; // stale, ignore\n  renderResults(results);\n}`,
    commonWrongAnswer: "\"Race conditions can't happen in JavaScript since it's single-threaded.\" — single-threaded execution doesn't guarantee ordered completion of concurrent async operations.",
    interviewTrap: "Ask how you'd prevent a slow, outdated network response from overwriting a newer one already on screen — the request-id/token pattern is the expected, production-grade answer.",
    followUp: "How does AbortController offer a more direct solution to this same problem?",
  },
  {
    slug: "async-error-handling",
    question: "How should errors be handled in async/await code?",
    category: "Async",
    difficulty: "medium",
    shortAnswer: "Wrap awaited calls in try/catch; an uncaught rejection inside an async function becomes a rejected Promise the caller must also handle.",
    deepExplanation: "A thrown error (or a rejected awaited Promise) inside an async function does not crash the whole program synchronously — it causes the async function's own returned Promise to reject. If nothing ever calls .catch() on that Promise (or wraps the awaiting code in its own try/catch), the rejection becomes an 'unhandled promise rejection', which many environments log as a warning or error without stopping execution.",
    codeExample: `async function loadUser(id) {\n  try {\n    const response = await fetch(\`/users/${"${id}"}\`);\n    if (!response.ok) throw new Error("Request failed");\n    return await response.json();\n  } catch (error) {\n    console.error("Failed to load user:", error.message);\n    return null;\n  }\n}`,
    commonWrongAnswer: "\"fetch() rejects automatically on a 404 or 500.\" — it does not; only network-level failures reject fetch, so response.ok must be checked manually.",
    interviewTrap: "Ask what happens to an error thrown inside an async function with no try/catch and no caller-side .catch() — many underestimate that it's a real, observable 'unhandled rejection', not silently swallowed.",
    followUp: "What's the difference between an unhandled promise rejection and an uncaught synchronous exception?",
  },

  // ---------------------------------------------------------------- Event Loop
  {
    slug: "what-is-the-call-stack",
    question: "What is the call stack, and how does it relate to a 'stack overflow'?",
    category: "Event Loop",
    difficulty: "easy",
    shortAnswer: "The call stack tracks nested function calls; a stack overflow happens when calls (often unterminated recursion) nest deeper than the engine's stack size limit.",
    deepExplanation: "Every function call pushes a new frame onto the call stack, and returning pops it off — this is how the engine knows which function to resume when the current one finishes. Recursion without a proper base case keeps pushing new frames until the stack's fixed size limit is exceeded, throwing a RangeError: Maximum call stack size exceeded.",
    codeExample: `function recurse() {\n  return recurse(); // no base case\n}\nrecurse(); // RangeError: Maximum call stack size exceeded`,
    commonWrongAnswer: "\"Stack overflow means the program ran out of memory generally.\" — it's specifically the call stack's frame limit, a fixed and much smaller boundary than total heap memory.",
    interviewTrap: "Ask how tail-call optimization theoretically helps here — note that despite being in the ES6 spec, it's not implemented in most major engines today, so recursion depth limits are a real practical concern.",
    followUp: "How would you rewrite unbounded recursion as an iterative loop to avoid the risk entirely?",
  },
  {
    slug: "microtask-vs-macrotask",
    question: "What is the difference between microtasks and macrotasks?",
    category: "Event Loop",
    difficulty: "hard",
    shortAnswer: "Microtasks (Promise callbacks, queueMicrotask) always run to completion before the next macrotask (setTimeout, I/O, UI events) is allowed to start.",
    deepExplanation: "After each macrotask finishes and the call stack empties, the event loop fully drains the microtask queue — running every queued microtask, including any new ones added during that draining — before picking up the next macrotask. This is why a Promise .then() reliably runs before the next setTimeout(fn, 0), no matter how many microtasks are queued.",
    codeExample: `console.log("1");\nsetTimeout(() => console.log("2 - macrotask"), 0);\nPromise.resolve().then(() => console.log("3 - microtask"));\nconsole.log("4");\n// order: 1, 4, 3, 2`,
    commonWrongAnswer: "\"They both just run in the order they were written.\" — queue priority overrides writing order for anything asynchronous.",
    interviewTrap: "This 1-4-3-2 ordering question is one of the single most common JavaScript interview questions — be ready to trace it instantly.",
    followUp: "What happens if a microtask callback queues another microtask — does it get processed in the same drain cycle?",
  },
  {
    slug: "why-ui-doesnt-freeze",
    question: "Why doesn't the browser UI freeze while waiting for an async operation like fetch?",
    category: "Event Loop",
    difficulty: "medium",
    shortAnswer: "The actual network request is handled by the browser's Web APIs outside the JavaScript thread; JavaScript only resumes (via the event loop) once the result is ready, so the main thread stays free to render and respond to input in the meantime.",
    deepExplanation: "JavaScript itself is single-threaded, but the browser provides separate threads/processes for things like network requests, timers, and file I/O. fetch() hands the actual request off to the browser, immediately returning a pending Promise, letting the main thread continue rendering and handling clicks. Only once the network response is ready does the event loop schedule the corresponding .then()/await continuation back onto the main thread.",
    codeExample: `console.log("start");\nfetch("/data").then(() => console.log("data ready"));\nconsole.log("end"); // UI remains responsive between start/end and \"data ready\"`,
    commonWrongAnswer: "\"JavaScript has background threads that run your async callbacks.\" — your callback code always runs on the single main JS thread; only the waiting happens elsewhere.",
    interviewTrap: "Clarify that Web Workers are the actual mechanism for running JS on another thread — fetch/setTimeout do NOT use worker threads for your callback code itself.",
    followUp: "How does a Web Worker differ from this Web API model in terms of where your code actually executes?",
  },
  {
    slug: "raf-vs-settimeout",
    question: "What is the difference between requestAnimationFrame and setTimeout for animations?",
    category: "Event Loop",
    difficulty: "medium",
    shortAnswer: "requestAnimationFrame syncs your callback to the browser's actual repaint cycle (typically 60fps); setTimeout runs on a fixed delay unrelated to rendering, which can cause dropped or misaligned frames.",
    deepExplanation: "requestAnimationFrame schedules a callback to run right before the browser's next repaint, automatically pausing in background/inactive tabs to save battery and CPU. setTimeout has no awareness of the rendering pipeline, so animating with it can produce frames that are out of sync with the display's actual refresh, and it keeps running (wastefully) even in a backgrounded tab unless separately guarded.",
    codeExample: `function animate() {\n  moveElementOneStep();\n  requestAnimationFrame(animate); // synced to next repaint\n}\nrequestAnimationFrame(animate);`,
    commonWrongAnswer: "\"setTimeout(fn, 16) is basically the same as requestAnimationFrame.\" — it approximates the interval but has none of the repaint-syncing or battery-saving behavior.",
    interviewTrap: "Ask what happens to requestAnimationFrame callbacks when the browser tab is inactive — they're throttled/paused automatically, unlike setTimeout.",
    followUp: "How would you build a simple animation loop with requestAnimationFrame that adjusts for variable frame timing (delta time)?",
  },

  // ---------------------------------------------------------------- Closures
  {
    slug: "what-is-a-closure",
    question: "What is a closure?",
    category: "Closures",
    difficulty: "medium",
    shortAnswer: "A closure is a function that retains access to variables from the scope it was defined in, even after that outer scope has finished executing.",
    deepExplanation: "Every function in JavaScript forms a closure over its lexical scope at creation time. This means a returned inner function keeps a live reference to the outer function's variables — not a snapshot — so later mutations to those variables (by the closure itself) are visible on the next call. This is the mechanism behind private state, factory functions, and memoization.",
    codeExample: `function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\nconst counter = makeCounter();\nconsole.log(counter(), counter(), counter()); // 1 2 3`,
    commonWrongAnswer: "\"A closure is just a nested function.\" — nesting alone isn't enough; a closure specifically means the inner function is retaining access to the outer scope's variables after that scope would otherwise have ended.",
    interviewTrap: "Ask whether two separate calls to makeCounter() share the same `count` — they don't, since each call creates a fresh, independent closure.",
    followUp: "How would closures let you implement a module with truly private variables before # private fields existed?",
  },
  {
    slug: "closures-private-state",
    question: "How can closures be used to create private variables?",
    category: "Closures",
    difficulty: "medium",
    shortAnswer: "A variable declared inside a function and never directly exposed can only be read or changed through functions returned from that same scope, effectively making it private.",
    deepExplanation: "This 'module pattern' predates class private fields (#field) and is still common in factory functions and IIFE-based modules: the outer function's local variable is invisible to outside code entirely, and the only way to interact with it is through whatever accessor/mutator functions the outer function chooses to expose.",
    codeExample: `function createBankAccount(initialBalance) {\n  let balance = initialBalance; // truly private — no external access path\n  return {\n    deposit(amount) { balance += amount; },\n    getBalance() { return balance; },\n  };\n}\nconst account = createBankAccount(100);\naccount.balance; // undefined — no direct access exists`,
    commonWrongAnswer: "\"You could still access balance with account._balance or similar.\" — with a true closure (unlike a convention like _balance), there is genuinely no property to access at all.",
    interviewTrap: "Ask how this compares to the newer #privateField class syntax — both achieve true privacy, but via different mechanisms (closures vs a language-level access restriction).",
    followUp: "What's a downside of the closure/factory-function pattern compared to classes, especially at scale?",
  },
  {
    slug: "closures-in-loops",
    question: "Why do closures created inside a var-based loop often reference the same value?",
    category: "Closures",
    difficulty: "hard",
    shortAnswer: "var is function-scoped, so every closure created in the loop shares the single, same variable — by the time any closure runs, the loop has already finished and the variable holds its final value.",
    deepExplanation: "Since var ignores block scope, there is exactly one `i` binding for the entire loop, not one per iteration. Every function created inside the loop closes over that one shared binding, so when they later execute (e.g., in a setTimeout callback), they all read whatever value `i` ended up with after the loop completed. Switching to let creates a fresh, independent binding of `i` for every single iteration, which is precisely what most people actually want.",
    codeExample: `for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}\n// logs: 3, 3, 3\n\nfor (let j = 0; j < 3; j++) {\n  setTimeout(() => console.log(j), 0);\n}\n// logs: 0, 1, 2`,
    commonWrongAnswer: "\"setTimeout somehow delays evaluation of `i` itself.\" — the callback body isn't evaluated until it runs, but which `i` it's reading depends entirely on var vs let scoping, not on setTimeout.",
    interviewTrap: "This is arguably THE most-asked closures question — be ready to explain it precisely, including naming the fix (let, or an IIFE capturing the value per iteration in older code).",
    followUp: "Before let existed, how would you have solved this with an IIFE?",
  },
  {
    slug: "closures-memory",
    question: "Can closures cause memory leaks?",
    category: "Closures",
    difficulty: "hard",
    shortAnswer: "Yes — a closure keeps its entire outer scope's variables alive in memory for as long as the closure itself is reachable, which can unintentionally retain large objects far longer than intended.",
    deepExplanation: "Because a closure holds a live reference to its defining scope, any large object referenced in that scope cannot be garbage collected while the closure exists, even if the closure never actually uses that particular object. This becomes a real leak when long-lived closures (like event listeners never removed, or timers never cleared) are created inside a scope that also happens to hold large or numerous objects.",
    codeExample: `function attachHandler(largeData) {\n  // even if the handler never reads largeData, it keeps it alive\n  element.addEventListener("click", () => console.log("clicked"));\n}\n// removing the element without removeEventListener can still leak in some engines`,
    commonWrongAnswer: "\"Closures are always safe since JavaScript has garbage collection.\" — garbage collection only frees memory nothing can still reach; a live closure counts as reachability, even accidentally.",
    interviewTrap: "Ask how you'd audit for this kind of leak in a long-running single-page app — looking for un-removed event listeners and uncanceled timers/intervals holding closures is the expected answer.",
    followUp: "Why is removeEventListener necessary even after the element itself is removed from the DOM?",
  },

  // ---------------------------------------------------------------- this
  {
    slug: "this-in-regular-function",
    question: "How is `this` determined inside a regular function?",
    category: "this",
    difficulty: "medium",
    shortAnswer: "`this` is set by how the function is called (the 'call site'), not by where it's defined — calling obj.method() binds this to obj; calling the same function detached binds this to undefined (strict mode) or the global object (sloppy mode).",
    deepExplanation: "JavaScript's `this` binding is dynamic and determined at call time by one of several rules, roughly in priority order: `new Foo()` binds this to the newly created object; `fn.call(obj)`/`fn.apply(obj)`/`fn.bind(obj)` explicitly set this to obj; `obj.method()` binds this to obj; and a bare function call binds this to undefined in strict mode (or the global object in sloppy mode).",
    codeExample: `const user = { name: "Ada", greet() { return this.name; } };\nconsole.log(user.greet()); // "Ada" — called as user.greet()\n\nconst detached = user.greet;\nconsole.log(detached()); // TypeError or undefined — this is lost`,
    commonWrongAnswer: "\"this refers to the object the method is defined inside.\" — this describes lexical scoping, which is NOT how regular function `this` works; it's about how the function is called.",
    interviewTrap: "Passing obj.method as a callback (e.g. to addEventListener or setTimeout) and then being surprised `this` is wrong is one of the most common real-world `this` bugs — be ready to name .bind() or an arrow wrapper as the fix.",
    followUp: "How does strict mode change what `this` is inside a bare function call?",
  },
  {
    slug: "this-in-arrow-function",
    question: "How does `this` behave differently inside an arrow function?",
    category: "this",
    difficulty: "medium",
    shortAnswer: "Arrow functions don't have their own `this` at all — they lexically inherit `this` from the enclosing scope where they were defined, and that binding can never be changed by how the arrow is called.",
    deepExplanation: "Unlike regular functions, arrow functions capture `this` from their surrounding lexical context at creation time, exactly like they do for any other variable. This makes them ideal for callbacks that need to preserve an outer `this` (like inside a class method), but means call(), apply(), and bind() cannot override an arrow function's `this`.",
    codeExample: `class Timer {\n  seconds = 0;\n  start() {\n    setInterval(() => {\n      this.seconds++; // arrow inherits this from start()\n    }, 1000);\n  }\n}`,
    commonWrongAnswer: "\"Arrow functions bind this to the global object.\" — they bind to nothing of their own; they transparently reuse whatever `this` already means at their definition site.",
    interviewTrap: "Ask what happens if you define an object method AS an arrow function (not nested inside a regular method) — `this` inside it will NOT refer to the object, a very common real bug.",
    followUp: "Why would defining a top-level object method as an arrow function be a mistake?",
  },
  {
    slug: "call-apply-bind",
    question: "What is the difference between call, apply, and bind?",
    category: "this",
    difficulty: "medium",
    shortAnswer: "call and apply both invoke a function immediately with an explicit `this` (call takes arguments individually, apply takes an array); bind returns a new function with `this` permanently fixed, without calling it.",
    deepExplanation: "All three let you explicitly control a function's `this` binding rather than relying on the call site. fn.call(obj, a, b) and fn.apply(obj, [a, b]) both execute fn right away with this set to obj, differing only in how arguments are passed. fn.bind(obj) instead returns a brand-new function permanently bound to obj — calling that new function later always uses the bound this, regardless of how IT is called.",
    codeExample: `function greet(greeting) { return \`${"${greeting}"}, ${"${this.name}"}\`; }\nconst user = { name: "Ada" };\ngreet.call(user, "Hi");        // "Hi, Ada" — runs immediately\ngreet.apply(user, ["Hi"]);     // "Hi, Ada" — runs immediately, args as array\nconst bound = greet.bind(user);\nbound("Hi");                    // "Hi, Ada" — can be called any time later`,
    commonWrongAnswer: "\"bind calls the function immediately just like call.\" — bind is the one exception; it only prepares a new function, it doesn't invoke anything.",
    interviewTrap: "A quick memory trick interviewers expect: 'A for Array (apply), C for Comma-separated (call)' — be ready to demonstrate you know the argument-passing difference instantly.",
    followUp: "Once a function is bound with .bind(), can a later .call() override its `this` again?",
  },
  {
    slug: "this-in-class-methods",
    question: "How does `this` behave in class methods, and why do class methods often need to be bound?",
    category: "this",
    difficulty: "hard",
    shortAnswer: "Class methods are regular functions attached to the prototype, so `this` still depends on the call site — passing a method as a callback (e.g. to an event listener) detaches it from the instance and loses `this`.",
    deepExplanation: "Even though a method is written inside a class body, JavaScript doesn't magically permanently bind `this` to the instance. If you extract the method (button.addEventListener('click', instance.handleClick)), it's called as a bare function, losing its `this`. Common fixes are binding in the constructor (this.handleClick = this.handleClick.bind(this)), or defining the method as a class field arrow function, which captures `this` lexically from the constructor's scope at instance-creation time.",
    codeExample: `class Button {\n  label = "Save";\n  // arrow class field: this is permanently the instance\n  handleClick = () => {\n    console.log(this.label);\n  };\n}\nconst btn = new Button();\nelement.addEventListener("click", btn.handleClick); // works correctly`,
    commonWrongAnswer: "\"Methods defined inside a class automatically keep `this` bound to the instance no matter how you call them.\" — only true for arrow-function class fields, not regular class methods.",
    interviewTrap: "Ask why a regular (non-arrow) class method passed directly as a callback logs `this` as undefined — many candidates assume classes solve this automatically.",
    followUp: "What's the tradeoff of using arrow function class fields for every method instead of regular methods?",
  },
  {
    slug: "losing-this-context",
    question: "Give a concrete example of 'losing this context' and how to fix it.",
    category: "this",
    difficulty: "medium",
    shortAnswer: "Passing an object method as a bare callback — like setTimeout(obj.method, 1000) — detaches it from obj, so `this` inside it is no longer obj when it eventually runs.",
    deepExplanation: "setTimeout invokes its callback as a plain function call, not as obj.method() — so whatever `this` the function relied on is gone. The three standard fixes are: wrap the call in an arrow function (setTimeout(() => obj.method(), 1000)), pre-bind it (setTimeout(obj.method.bind(obj), 1000)), or define the method itself as an arrow function class field so it's always bound to the instance.",
    codeExample: `const timer = {\n  seconds: 0,\n  tick() { this.seconds++; console.log(this.seconds); },\n};\nsetTimeout(timer.tick, 1000); // TypeError: this.seconds is undefined-ish\nsetTimeout(() => timer.tick(), 1000); // works — this.seconds increments`,
    commonWrongAnswer: "\"Since tick is defined on timer, it will always know it belongs to timer.\" — a function's definition location never determines its `this`; only the call site does.",
    interviewTrap: "Ask candidates to fix the buggy setTimeout(timer.tick, 1000) line live — there are three valid fixes, and naming more than one shows depth.",
    followUp: "Why does wrapping in an arrow function fix it, given arrow functions have no `this` of their own?",
  },

  // ---------------------------------------------------------------- Prototypes
  {
    slug: "prototype-chain-interview",
    question: "What is the prototype chain?",
    category: "Prototypes",
    difficulty: "medium",
    shortAnswer: "Every object has an internal link to another object (its prototype); when a property lookup fails on the object itself, JavaScript searches up this chain of prototypes until it finds the property or reaches null.",
    deepExplanation: "This is how built-in methods like array.map() or object.hasOwnProperty() work without being copied onto every single instance — they live once on Array.prototype or Object.prototype, and instances delegate lookups up the chain to find them. The chain always terminates at Object.prototype, whose own prototype is null, ending the search.",
    codeExample: `const arr = [1, 2, 3];\narr.hasOwnProperty(0); // true — found directly on arr\n// arr -> Array.prototype (has .map, .filter...) -> Object.prototype -> null\nconsole.log(Object.getPrototypeOf(Object.getPrototypeOf(arr)) === Object.prototype); // true`,
    commonWrongAnswer: "\"Every array carries its own personal copy of .map, .filter, etc.\" — those methods are shared, defined once on Array.prototype, not duplicated per instance.",
    interviewTrap: "Ask what Object.getPrototypeOf(Object.prototype) returns — it's null, marking the very end of every prototype chain.",
    followUp: "How does this delegation model differ from classical (class-based) inheritance in languages like Java?",
  },
  {
    slug: "proto-vs-prototype",
    question: "What is the difference between __proto__ and .prototype?",
    category: "Prototypes",
    difficulty: "hard",
    shortAnswer: "`.prototype` is a property that only exists on functions/classes, defining what instances created with `new` will link to; `__proto__` is the actual internal link an object itself has to its prototype.",
    deepExplanation: "When you write `function Dog() {}`, Dog.prototype is an object that will become the prototype of every instance made with `new Dog()`. Once created, that instance's own internal prototype link is exposed (non-standard, but widely supported) as __proto__, and points to Dog.prototype. Object.getPrototypeOf(instance) is the modern, standard way to read that same link instead of __proto__.",
    codeExample: `function Dog() {}\nconst rex = new Dog();\nconsole.log(rex.__proto__ === Dog.prototype); // true\nconsole.log(Object.getPrototypeOf(rex) === Dog.prototype); // true, preferred`,
    commonWrongAnswer: "\"__proto__ and .prototype are just two names for the same thing.\" — .prototype belongs to constructor functions; __proto__ belongs to instances and points AT a constructor's .prototype.",
    interviewTrap: "Ask which of the two exists on a plain object literal ({}) versus a function — plain objects have __proto__ but no .prototype property.",
    followUp: "Why is Object.getPrototypeOf() preferred over accessing __proto__ directly in modern code?",
  },
  {
    slug: "object-create",
    question: "What does Object.create() do, and how is it different from using `new`?",
    category: "Prototypes",
    difficulty: "hard",
    shortAnswer: "Object.create(proto) creates a brand-new, empty object whose prototype is explicitly set to proto — no constructor function or `new` keyword is involved at all.",
    deepExplanation: "This offers direct, explicit control over the prototype chain without going through a constructor function's implicit rules. It's the mechanism ES6 classes use internally to set up inheritance (Dog.prototype = Object.create(Animal.prototype)), and is also useful for creating objects with no prototype at all (Object.create(null)) to avoid inherited properties like toString entirely.",
    codeExample: `const animal = { speak() { return "..."; } };\nconst dog = Object.create(animal);\ndog.speak(); // "..." — inherited via the prototype chain\n\nconst pureMap = Object.create(null); // no Object.prototype methods at all\npureMap.toString; // undefined`,
    commonWrongAnswer: "\"Object.create() runs a constructor function like new does.\" — it does not call anything; it only sets up the prototype link on a fresh, otherwise empty object.",
    interviewTrap: "Ask why you might use Object.create(null) for a lookup dictionary — avoiding accidental collisions with inherited keys like `constructor` or `toString` is the key insight.",
    followUp: "How did ES6 class extends use Object.create internally before classes existed as syntax?",
  },
  {
    slug: "class-vs-prototype",
    question: "Are ES6 classes a fundamentally new inheritance model, or syntax over prototypes?",
    category: "Prototypes",
    difficulty: "medium",
    shortAnswer: "ES6 class syntax is primarily 'syntactic sugar' over the existing prototype-based inheritance model — under the hood, methods still live on .prototype and instances still delegate through the same chain.",
    deepExplanation: "A class's methods (other than static ones) are installed on ClassName.prototype exactly as if you'd written Dog.prototype.speak = function () {...} manually. `extends` sets up the same Object.create-based prototype chain a manual constructor-function pattern would. Classes do add a few genuinely new behaviors on top though — like requiring `new` (calling a class without new throws), and enforcing that a subclass constructor call super() before using `this`.",
    codeExample: `class Dog {\n  speak() { return "Woof"; }\n}\nconsole.log(typeof Dog.prototype.speak); // "function" — same underlying mechanism`,
    commonWrongAnswer: "\"Classes in JavaScript work exactly like classes in Java or C++, with no relation to prototypes.\" — the underlying delegation mechanism is identical to plain prototype-based objects.",
    interviewTrap: "Ask what happens if you call a class as a plain function (Dog() without new) — it throws a TypeError, unlike old-style constructor functions, which is a genuine behavioral difference worth naming.",
    followUp: "What actually happens if a derived class constructor tries to use `this` before calling super()?",
  },

  // ---------------------------------------------------------------- Performance
  {
    slug: "debounce-vs-throttle-interview",
    question: "What is the difference between debounce and throttle, and when would you use each?",
    category: "Performance",
    difficulty: "medium",
    shortAnswer: "Debounce delays execution until a burst of calls pauses; throttle guarantees execution at most once per fixed interval regardless of how many calls happen.",
    deepExplanation: "Debounce is ideal for 'wait until the user stops' scenarios like search-as-you-type or resize-end handling, where only the final state matters. Throttle is ideal for 'at most this often' scenarios like scroll position tracking or a button that shouldn't be spammable, where you want periodic execution throughout, not just at the end.",
    codeExample: `const debouncedSearch = debounce(runSearch, 300);   // waits for typing to pause\nconst throttledScroll = throttle(updatePosition, 100); // runs at most every 100ms`,
    commonWrongAnswer: "\"They're interchangeable performance optimizations.\" — using the wrong one produces a genuinely different (and often broken-feeling) user experience.",
    interviewTrap: "Ask for a real scenario where using debounce instead of throttle (or vice versa) would create a noticeably bad UX — infinite scroll debounced instead of throttled is a good example (it would never fire while scrolling continuously).",
    followUp: "How would you implement a throttle that also guarantees a final trailing call after the last invocation?",
  },
  {
    slug: "memoization-interview",
    question: "What is memoization, and what are its tradeoffs?",
    category: "Performance",
    difficulty: "medium",
    shortAnswer: "Memoization caches a pure function's output keyed by its input, trading memory for avoiding redundant computation — but it's only safe for pure functions and can grow memory usage unboundedly if not managed.",
    deepExplanation: "It's most valuable for expensive, frequently-repeated computations with a limited set of realistic inputs (recursive algorithms, expensive derived UI values). The tradeoff is real: the cache consumes memory for every unique input ever seen, so a naive unbounded cache in a long-running process (or with highly variable inputs) can itself become a memory problem — bounded caches (LRU) or clearing strategies are often needed in production.",
    codeExample: `const memoizedFib = memoize(function fib(n) {\n  return n <= 1 ? n : memoizedFib(n - 1) + memoizedFib(n - 2);\n});`,
    commonWrongAnswer: "\"Memoization is always a free performance win with no downsides.\" — unbounded caches and impure functions are two real ways it backfires.",
    interviewTrap: "Ask what would go wrong if you memoized a function that also has a side effect, like incrementing an external counter, or that returns different results based on the current time — both break the correctness of caching.",
    followUp: "How would you implement an LRU (least-recently-used) eviction policy for a memoization cache?",
  },
  {
    slug: "virtual-dom-concept",
    question: "What problem does a 'virtual DOM' (as used by React) actually solve?",
    category: "Performance",
    difficulty: "medium",
    shortAnswer: "It lets a framework compute the minimal set of real DOM changes needed for a new UI state by diffing lightweight JavaScript object trees, instead of the developer manually tracking and applying every DOM mutation.",
    deepExplanation: "Directly mutating the real DOM is comparatively expensive due to layout/reflow costs, and manually tracking exactly which parts of a complex UI changed is error-prone. A virtual DOM represents the desired UI as a plain JS object tree; on each update, the framework diffs the new tree against the previous one and applies only the necessary real DOM operations — batched efficiently. It's a means to an end (developer ergonomics + reasonably efficient updates), not automatically 'faster than the DOM' in every case.",
    codeExample: `// conceptually:\nconst newTree = render(state);\nconst patches = diff(oldTree, newTree);\napplyPatches(realDOM, patches); // only touches what actually changed`,
    commonWrongAnswer: "\"A virtual DOM is always faster than directly manipulating the real DOM.\" — hand-optimized direct DOM manipulation can outperform it; the real win is maintainable, declarative code with good-enough performance by default.",
    interviewTrap: "Ask what the virtual DOM does NOT solve — it doesn't eliminate the cost of the initial full render, and naive re-renders of huge trees can still be slow without techniques like keys and memoization.",
    followUp: "What role do 'keys' play when diffing a list of virtual DOM nodes?",
  },
  {
    slug: "avoiding-memory-leaks",
    question: "What are common causes of memory leaks in browser JavaScript, and how do you avoid them?",
    category: "Performance",
    difficulty: "hard",
    shortAnswer: "The most common causes are event listeners never removed, timers/intervals never cleared, and closures unintentionally retaining large objects — all of which keep memory reachable long after it's actually needed.",
    deepExplanation: "The browser's garbage collector only frees memory nothing can reach anymore, so any lingering reference — a global variable, an un-removed event listener on a detached element, an active setInterval, or a closure capturing more than it needs — prevents collection indefinitely. The fix in each case is symmetry: every addEventListener paired with a removeEventListener, every setInterval paired with a clearInterval, and being deliberate about what a returned closure actually needs to capture.",
    codeExample: `function setup() {\n  const handler = () => console.log("resized");\n  window.addEventListener("resize", handler);\n  return () => window.removeEventListener("resize", handler); // cleanup\n}\nconst cleanup = setup();\n// later: cleanup();`,
    commonWrongAnswer: "\"Garbage collection means I never need to think about cleanup in JavaScript.\" — GC only reclaims genuinely unreachable memory; leaked references defeat it entirely.",
    interviewTrap: "Ask specifically about React's useEffect cleanup function — it exists precisely to pair every subscription/listener/timer with its teardown, directly applying this principle.",
    followUp: "How would you use the browser DevTools Memory tab to actually confirm a suspected leak?",
  },

  // ---------------------------------------------------------------- Algorithms
  {
    slug: "common-time-complexities",
    question: "What is the time complexity of common array and object operations?",
    category: "Algorithms",
    difficulty: "medium",
    shortAnswer: "Array push/pop and object/Map/Set get-set-has are O(1); array unshift/shift, indexOf/includes, and splice are O(n); nested loops over the same data are typically O(n²).",
    deepExplanation: "push/pop operate at the end of an array so no other elements move — O(1). unshift/shift/splice at the front must re-index every following element — O(n). Object and Map property/key lookups are effectively O(1) via hashing. Array.includes/indexOf/find must scan linearly in the worst case — O(n). Knowing these lets you predict whether an approach will still be fast at 10x the data.",
    codeExample: `arr.push(x);      // O(1)\narr.unshift(x);    // O(n) — reindexes everything\narr.includes(x);   // O(n) — worst case scans the whole array\nmap.get(key);      // O(1) average`,
    commonWrongAnswer: "\"All array methods have roughly the same cost.\" — the position and nature of the operation matters enormously at scale.",
    interviewTrap: "Ask why repeatedly calling array.includes() inside a loop over another array is a hidden O(n²) — a very common accidental performance bug in real code.",
    followUp: "How would you rewrite a nested-loop duplicate check to run in O(n) instead?",
  },
  {
    slug: "two-pointer-technique",
    question: "What is the two-pointer technique, and when is it useful?",
    category: "Algorithms",
    difficulty: "medium",
    shortAnswer: "Two-pointer uses two index variables moving through a (usually sorted) array — often from opposite ends or at different speeds — to solve problems in O(n) that would otherwise need nested loops.",
    deepExplanation: "A classic use is finding a pair in a sorted array summing to a target: start one pointer at the beginning, one at the end, and move whichever pointer would bring the sum closer to the target, narrowing the search space by one element every step instead of comparing every pair.",
    codeExample: `function hasPairWithSum(sorted, target) {\n  let left = 0, right = sorted.length - 1;\n  while (left < right) {\n    const sum = sorted[left] + sorted[right];\n    if (sum === target) return true;\n    if (sum < target) left++; else right--;\n  }\n  return false;\n}`,
    commonWrongAnswer: "\"Two-pointer only works for finding pairs.\" — it also applies to problems like removing duplicates in place, reversing an array, or detecting palindromes.",
    interviewTrap: "Ask why this technique requires the input to be sorted first — the pointer-moving logic depends entirely on knowing which direction increases or decreases the sum.",
    followUp: "How would you adapt two-pointer to find a palindrome without creating a reversed copy of the string?",
  },
  {
    slug: "recursion-vs-iteration",
    question: "When would you choose recursion over iteration, and what are the tradeoffs?",
    category: "Algorithms",
    difficulty: "medium",
    shortAnswer: "Recursion often expresses naturally hierarchical or divide-and-conquer problems (tree traversal, nested data) more clearly, but risks stack overflow on deep inputs, whereas iteration is typically more memory-efficient and safer for large inputs.",
    deepExplanation: "Problems with a naturally recursive structure — traversing a nested object of unknown depth, or classic divide-and-conquer algorithms — are often far more readable recursively than iteratively. However, since most JavaScript engines don't implement tail-call optimization, deep recursion (thousands of levels) risks RangeError: Maximum call stack exceeded, where an equivalent loop-based (often with an explicit stack) solution would not.",
    codeExample: `// recursive — clear, but risks stack overflow on very deep trees\nfunction countNodes(node) {\n  if (!node) return 0;\n  return 1 + node.children.reduce((sum, c) => sum + countNodes(c), 0);\n}`,
    commonWrongAnswer: "\"Recursion is always slower than iteration.\" — for shallow, naturally recursive problems the difference is negligible; the real risk is stack depth on large inputs, not raw speed.",
    interviewTrap: "Ask how you would convert a recursive traversal into an iterative one using an explicit stack array — a common 'prove you understand the underlying mechanism' request.",
    followUp: "Why doesn't JavaScript's lack of guaranteed tail-call optimization matter for shallow recursion?",
  },
  {
    slug: "sorting-tradeoffs",
    question: "What are the tradeoffs between common sorting algorithms like bubble sort, merge sort, and quicksort?",
    category: "Algorithms",
    difficulty: "hard",
    shortAnswer: "Bubble sort is simple but O(n²); merge sort guarantees O(n log n) with extra memory for merging; quicksort averages O(n log n) in-place but degrades to O(n²) in a worst-case pivot scenario.",
    deepExplanation: "Bubble sort's simplicity makes it a good teaching tool, but its quadratic behavior makes it impractical for real datasets of meaningful size. Merge sort's divide-and-conquer approach guarantees O(n log n) regardless of input order, at the cost of O(n) auxiliary memory for merging. Quicksort is typically faster in practice and sorts in place (less memory), but a poorly chosen pivot on already-sorted or adversarial data can degrade it to O(n²) — real implementations mitigate this with randomized or median-of-three pivot selection.",
    codeExample: `// V8's Array.prototype.sort uses TimSort for larger arrays —\n// a hybrid, stable, O(n log n) algorithm — not any single classic one.\n[3, 1, 2].sort((a, b) => a - b);`,
    commonWrongAnswer: "\"You should always implement your own sort for performance.\" — built-in Array.prototype.sort is a well-optimized, battle-tested hybrid algorithm; hand-rolled sorts are almost always worse in practice.",
    interviewTrap: "Ask what algorithm Array.prototype.sort actually uses under the hood in V8 — knowing it's TimSort (not simply quicksort) signals real depth beyond memorized Big O tables.",
    followUp: "Why is a stable sort (preserving the relative order of equal elements) sometimes an important guarantee?",
  },
  {
    slug: "map-vs-object-for-lookup",
    question: "When should you use a Map instead of a plain object for key-value storage?",
    category: "Algorithms",
    difficulty: "medium",
    shortAnswer: "Use a Map when keys aren't simple strings, when insertion order matters reliably, or when you need frequent additions/removals — a Map has no inherited properties and offers O(1) size tracking and iteration in insertion order.",
    deepExplanation: "Plain objects coerce all keys to strings (or use Symbols), inherit properties from Object.prototype (a source of accidental collisions), and require Object.keys(obj).length to count entries. Map accepts any value as a key (including objects and functions), maintains guaranteed insertion order during iteration, exposes a direct .size property, and has no prototype pollution risk since it doesn't inherit from Object.prototype in the same way for its stored data.",
    codeExample: `const cache = new Map();\nconst objKey = { id: 1 };\ncache.set(objKey, "value"); // objects as keys — impossible with plain objects\nconsole.log(cache.size);    // O(1), no Object.keys(...).length needed`,
    commonWrongAnswer: "\"Map and object are basically interchangeable for any key-value use case.\" — object keys are always coerced to strings, which silently breaks non-string-key use cases.",
    interviewTrap: "Ask what happens when you use an object as a plain-object key, like obj[someObject] = 1 — it gets stringified to '[object Object]', silently colliding with any other object used as a key the same way.",
    followUp: "Why might you still prefer a plain object over a Map for simple, known-shape configuration data?",
  },
];
