import type { QuizQuestion, WeeklyQuiz } from "@/types/learning";

function q(
  id: string,
  type: QuizQuestion["type"],
  skill: QuizQuestion["skill"],
  question: string,
  options: string[],
  answer: number,
  explanation: string,
  code?: string,
): QuizQuestion {
  return { id, type, skill, question, options, answer, explanation, code };
}

const week1: QuizQuestion[] = [
  q(
    "w1-q1",
    "multiple-choice",
    "fundamentals",
    "What does JavaScript use to track which function is currently executing?",
    ["The DOM", "The call stack", "localStorage", "The event loop"],
    1,
    "Each call pushes a frame onto the call stack and pops it off on return.",
  ),
  q(
    "w1-q2",
    "true-false",
    "variables",
    "const prevents the variable's value from ever changing, even for objects.",
    ["True", "False"],
    1,
    "const only prevents reassigning the binding itself — an object it points to can still be mutated.",
  ),
  q(
    "w1-q3",
    "predict-output",
    "data-types",
    "What does this log?",
    ["null", "undefined", '"object"', "Error"],
    2,
    'typeof null is a long-standing language quirk that returns "object".',
    "console.log(typeof null);",
  ),
  q(
    "w1-q4",
    "identify-error",
    "variables",
    "What is wrong with this code?",
    [
      "Nothing — it works fine",
      "const cannot be reassigned",
      "let is not allowed in loops",
      "Missing semicolon",
    ],
    1,
    "score is declared with const, so score = score + 1 throws a TypeError.",
    "const score = 0;\nscore = score + 1;",
  ),
  q(
    "w1-q5",
    "select-code",
    "strings",
    "Which snippet correctly interpolates name into a greeting?",
    [
      '"Hello, " . name',
      "'Hello, ${name}'",
      "`Hello, ${name}`",
      '"Hello, {name}"',
    ],
    2,
    "Backtick template literals are required for ${} interpolation to work.",
  ),
  q(
    "w1-q6",
    "scenario",
    "data-types",
    'What does "5" + 1 evaluate to?',
    ["6", '"51"', "NaN", "Error"],
    1,
    "+ prefers string concatenation whenever either operand is a string.",
  ),
  q(
    "w1-q7",
    "multiple-choice",
    "debugging",
    "What should you do first when debugging a failing program?",
    [
      "Rewrite it from scratch",
      "Reliably reproduce the failure",
      "Guess at a fix immediately",
      "Ask someone else to fix it",
    ],
    1,
    "You can't verify a fix without first being able to reliably reproduce the bug.",
  ),
  q(
    "w1-q8",
    "predict-output",
    "fundamentals",
    "What does this log?",
    ["true", "false", "Error", "undefined"],
    1,
    '=== compares type and value with no coercion, and "1" is a string while 1 is a number.',
    'console.log(1 === "1");',
  ),
  q(
    "w1-q9",
    "true-false",
    "data-types",
    'The empty string "" is falsy.',
    ["True", "False"],
    0,
    '"" is one of the six falsy values, alongside false, 0, null, undefined, and NaN.',
  ),
  q(
    "w1-q10",
    "scenario",
    "strings",
    "You need a multi-line string with an interpolated variable. What should you reach for?",
    [
      "String concatenation with +",
      "Template literals with backticks",
      "Regular single-quoted strings",
      "Array.join()",
    ],
    1,
    "Template literals support both multi-line strings and ${} interpolation in one syntax.",
  ),
];

const week2: QuizQuestion[] = [
  q(
    "w2-q1",
    "predict-output",
    "conditions",
    "What does this log?",
    ["Eligible", "Not yet", "undefined", "Error"],
    0,
    "18 >= 18 is true, so the eligible branch runs.",
    'function canVote(age) {\n  if (age >= 18) return "Eligible";\n  return "Not yet";\n}\nconsole.log(canVote(18));',
  ),
  q(
    "w2-q2",
    "true-false",
    "conditions",
    "An empty array [] is falsy in an if condition.",
    ["True", "False"],
    1,
    'Only false, 0, "", null, undefined, and NaN are falsy — [] and {} are both truthy.',
  ),
  q(
    "w2-q3",
    "identify-error",
    "functions",
    "What's wrong with this arrow function?",
    [
      "Nothing, it returns {id: 1}",
      "It returns undefined, not an object",
      "Arrow functions can't return objects",
      "It throws a SyntaxError",
    ],
    1,
    "The braces are parsed as a function body, not an object literal — wrap it in parens: () => ({id: 1}).",
    "const makeUser = () => { id: 1 };\nconsole.log(makeUser());",
  ),
  q(
    "w2-q4",
    "select-code",
    "functions",
    "Which correctly gives `decimals` a default value of 2?",
    [
      "function f(decimals == 2)",
      "function f(decimals: 2)",
      "function f(decimals = 2)",
      "function f(decimals ?? 2)",
    ],
    2,
    "Default parameters use `=` directly in the parameter list.",
  ),
  q(
    "w2-q5",
    "multiple-choice",
    "scope",
    "What makes a function 'pure'?",
    [
      "It never returns a value",
      "Its output depends only on its inputs, with no outside side effects",
      "It must be written as an arrow function",
      "It has no parameters",
    ],
    1,
    "Purity means predictable behavior based solely on arguments, with no external mutation.",
  ),
  q(
    "w2-q6",
    "predict-output",
    "loops",
    "How many times does 'lap' log?",
    ["2", "3", "4", "Infinite"],
    1,
    "The loop runs while i < 3, for i = 0, 1, 2 — three iterations.",
    'for (let i = 0; i < 3; i++) {\n  console.log("lap");\n}',
  ),
  q(
    "w2-q7",
    "true-false",
    "scope",
    "Arrow functions have their own `this` binding.",
    ["True", "False"],
    1,
    "Arrow functions inherit `this` lexically from their enclosing scope instead of having their own.",
  ),
  q(
    "w2-q8",
    "identify-error",
    "loops",
    "What bug causes this to never finish?",
    [
      "The condition is always false",
      "i is never updated toward the exit condition",
      "console.log is too slow",
      "There is no bug",
    ],
    1,
    "i++ moves i further from satisfying i > 0 being false, since it starts positive and counts up forever.",
    "for (let i = 5; i > 0; i++) {\n  console.log(i);\n}",
  ),
  q(
    "w2-q9",
    "scenario",
    "conditions",
    "You need to classify a score into A/B/C/D/F. What's the cleanest structure?",
    [
      "A single ternary with 5 branches",
      "Ordered if/return checks from highest to lowest boundary",
      "A random number generator",
      "Five separate functions",
    ],
    1,
    "Early returns checked from the highest boundary down avoid deep nesting entirely.",
  ),
  q(
    "w2-q10",
    "multiple-choice",
    "algorithms",
    "What should you do before writing code for a new problem?",
    [
      "Start typing immediately",
      "Restate the problem and trace a small example by hand",
      "Skip edge cases to save time",
      "Copy a solution from memory",
    ],
    1,
    "Restating the problem and tracing an example surfaces the pattern before committing to code.",
  ),
];

const week3: QuizQuestion[] = [
  q(
    "w3-q1",
    "predict-output",
    "arrays",
    "What does this log?",
    ["undefined", "3", "cherry", "Error"],
    2,
    'The last index of a 3-item array is length - 1, which is 2 — fruits[2] is "cherry".',
    'const fruits = ["apple", "banana", "cherry"];\nconsole.log(fruits[fruits.length - 1]);',
  ),
  q(
    "w3-q2",
    "true-false",
    "arrays",
    "Array.prototype.map() mutates the original array.",
    ["True", "False"],
    1,
    "map() always returns a brand-new array and never mutates the original.",
  ),
  q(
    "w3-q3",
    "identify-error",
    "arrays",
    "What's the bug?",
    [
      "sort() doesn't exist",
      "sort() with no comparator sorts numbers as strings",
      "The array is empty",
      "There is no bug",
    ],
    1,
    'Without a comparator, sort() converts to strings, producing [10, 2, 1] since "10" < "2" lexicographically.',
    "const nums = [10, 2, 1];\nconsole.log(nums.sort());",
  ),
  q(
    "w3-q4",
    "select-code",
    "objects",
    'Which correctly destructures name with a default role of "learner"?',
    [
      'const {name, role} = user ?? "learner"',
      'const {name, role = "learner"} = user',
      'const [name, role = "learner"] = user',
      'const name, role = "learner" = user',
    ],
    1,
    "Defaults inside destructuring use `= value` directly on the property being unpacked.",
  ),
  q(
    "w3-q5",
    "predict-output",
    "objects",
    "What does this log?",
    ["Ada", "Grace", "undefined", "Error"],
    1,
    "Objects are copied by reference — userB is the same object as userA, so mutating one affects both.",
    'const userA = { name: "Ada" };\nconst userB = userA;\nuserB.name = "Grace";\nconsole.log(userA.name);',
  ),
  q(
    "w3-q6",
    "scenario",
    "arrays",
    "You need every user's name where age > 18. What's the idiomatic approach?",
    [
      "A manual for loop with a push",
      "users.filter(u => u.age > 18).map(u => u.name)",
      "users.reduce with no initial value",
      "JSON.parse(JSON.stringify(users))",
    ],
    1,
    "filter narrows to matching users, then map extracts just the name field — clear and composable.",
  ),
  q(
    "w3-q7",
    "true-false",
    "objects",
    "Spreading an object ({...obj}) creates a fully independent deep copy.",
    ["True", "False"],
    1,
    "Spread is shallow — nested objects/arrays inside it are still shared by reference.",
  ),
  q(
    "w3-q8",
    "identify-error",
    "arrays",
    "Why does this return the wrong total?",
    [
      "reduce doesn't exist on arrays",
      "Missing an initial value, so the first element is used as the accumulator",
      "The array is empty",
      "prices should be an object",
    ],
    1,
    "Without an initial value, reduce uses the first element as the starting accumulator, which is usually not intended.",
    "const prices = [10, 20, 30];\nconst total = prices.reduce((sum, p) => sum + p);\nconsole.log(total);",
  ),
  q(
    "w3-q9",
    "multiple-choice",
    "arrays",
    "What does array.find() return when nothing matches?",
    ["null", "An empty array", "undefined", "It throws"],
    2,
    "find() returns undefined on no match, so the result should always be checked before use.",
  ),
  q(
    "w3-q10",
    "scenario",
    "objects",
    "You're reading a deeply nested API field that might not exist. What's the safest approach?",
    [
      "Assume it always exists",
      "user?.address?.city with optional chaining",
      "Wrap the whole app in try/catch",
      "Use eval()",
    ],
    1,
    "Optional chaining short-circuits to undefined the moment any link in the chain is missing, instead of throwing.",
  ),
];

const week4: QuizQuestion[] = [
  q(
    "w4-q1",
    "multiple-choice",
    "dom",
    "What does document.querySelector return when no element matches?",
    ["An empty string", "undefined", "null", "It throws"],
    2,
    "querySelector returns null on no match — always guard before using the result.",
  ),
  q(
    "w4-q2",
    "true-false",
    "events",
    "event.target is always the element the listener was attached to.",
    ["True", "False"],
    1,
    "event.target is the deepest element where the event actually originated, which can differ from event.currentTarget (where the listener lives).",
  ),
  q(
    "w4-q3",
    "identify-error",
    "dom",
    "What's the bug in this handler?",
    [
      "Nothing is wrong",
      "It doesn't call event.preventDefault(), so the page reloads",
      "addEventListener is misspelled",
      "submit events don't exist",
    ],
    1,
    "Without preventDefault(), the browser's default full-page reload/navigation on form submit still happens.",
    'form.addEventListener("submit", (event) => {\n  validateForm();\n});',
  ),
  q(
    "w4-q4",
    "scenario",
    "events",
    "You have a list where items are added dynamically. What's the best way to handle clicks on items?",
    [
      "Attach a new listener to every item as it's added",
      "One delegated listener on the parent list",
      "Poll the DOM every second for new items",
      "Use only inline onclick attributes",
    ],
    1,
    "Event delegation on a shared parent handles current AND future children with a single listener.",
  ),
  q(
    "w4-q5",
    "predict-output",
    "events",
    "In what order do bubble-phase listeners on child then parent fire for a click on child?",
    [
      "parent, then child",
      "child, then parent",
      "Only child fires",
      "Only parent fires",
    ],
    1,
    "During the bubble phase, the event fires on the target first, then propagates up through each ancestor.",
  ),
  q(
    "w4-q6",
    "true-false",
    "dom",
    "localStorage can store JavaScript objects directly, without conversion.",
    ["True", "False"],
    1,
    "localStorage only stores strings — objects must be JSON.stringify'd first and JSON.parse'd when read back.",
  ),
  q(
    "w4-q7",
    "select-code",
    "async",
    "Which correctly cancels a scheduled setTimeout before it fires?",
    [
      "timeout.cancel()",
      "clearTimeout(id)",
      "delete setTimeout(id)",
      "timeout.stop()",
    ],
    1,
    "clearTimeout(id), using the id returned by setTimeout, cancels a pending timer.",
  ),
  q(
    "w4-q8",
    "identify-error",
    "dom",
    "Why might this throw?",
    [
      "querySelector is misspelled",
      "The element might not exist, and .textContent is being set on null",
      "textContent isn't a real property",
      "There is no bug",
    ],
    1,
    "If no element matches the selector, querySelector returns null, and setting a property on null throws a TypeError.",
    'const el = document.querySelector(".missing");\nel.textContent = "Hi";',
  ),
  q(
    "w4-q9",
    "multiple-choice",
    "dom",
    "Why should you validate form input on the server even if you already validate on the client?",
    [
      "Server validation is optional if client validation exists",
      "Client-side code can be bypassed entirely by a motivated user",
      "It makes the page load faster",
      "There is no real reason",
    ],
    1,
    "A user can call your API directly, skipping the browser and any client-side checks entirely.",
  ),
  q(
    "w4-q10",
    "scenario",
    "events",
    "A 'remove item' button exists on every row of a table with hundreds of rows. What's the most memory-efficient listener strategy?",
    [
      "One listener per button (hundreds of listeners)",
      "One delegated listener on the table body",
      "Re-render the whole table on every click",
      "Use a global variable to track clicks",
    ],
    1,
    "Delegation avoids hundreds of individual listeners, using one listener and event.target to identify the row.",
  ),
];

const week5: QuizQuestion[] = [
  q(
    "w5-q1",
    "predict-output",
    "scope",
    "What does this log?",
    ["1 1", "1 2", "2 2", "undefined undefined"],
    1,
    "Each call to next() increments the same private `count` retained by the closure.",
    "function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\nconst next = makeCounter();\nconsole.log(next(), next());",
  ),
  q(
    "w5-q2",
    "true-false",
    "scope",
    "Two separate calls to the same closure-returning function share one private variable.",
    ["True", "False"],
    1,
    "Each call creates a brand-new, independent closure with its own private variable.",
  ),
  q(
    "w5-q3",
    "identify-error",
    "scope",
    "Why do all three callbacks log 3?",
    [
      "setTimeout is broken",
      "var is function-scoped, so all closures share one `i`, which is 3 after the loop ends",
      "console.log doesn't work in loops",
      "There is no bug",
    ],
    1,
    "Switching var to let would give each iteration its own `i`, fixing the bug.",
    "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
  ),
  q(
    "w5-q4",
    "multiple-choice",
    "scope",
    "What determines the value of `this` inside a regular function?",
    [
      "Where the function is defined",
      "How the function is called",
      "The function's name",
      "Its parameter list",
    ],
    1,
    "`this` is bound dynamically at the call site, not lexically at the function's definition.",
  ),
  q(
    "w5-q5",
    "predict-output",
    "objects",
    "What does this log?",
    ["Grace", "Ada", "undefined", "Error"],
    0,
    "Assignment copies the reference — userA and userB point to the same object, so mutating through userB affects userA too.",
    'const userA = { name: "Ada" };\nconst userB = userA;\nuserB.name = "Grace";\nconsole.log(userA.name);',
  ),
  q(
    "w5-q6",
    "true-false",
    "objects",
    "A class's private #field is accessible from outside the class if you know the field name.",
    ["True", "False"],
    1,
    "Private fields are enforced by the language — accessing #field outside the class body is a SyntaxError, not just discouraged.",
  ),
  q(
    "w5-q7",
    "select-code",
    "objects",
    "Which correctly calls the parent constructor in a subclass?",
    ["this.parent()", "super()", "Parent.constructor()", "extends()"],
    1,
    "super() invokes the parent class's constructor and must run before `this` is used.",
  ),
  q(
    "w5-q8",
    "scenario",
    "scope",
    "You pass obj.method as a callback to setTimeout and `this` inside it is now wrong. What's a valid fix?",
    [
      "Rename the method",
      "setTimeout(() => obj.method(), 1000) or bind it first",
      "Make the method a global function",
      "It cannot be fixed",
    ],
    1,
    "Wrapping in an arrow function (or using .bind(obj)) preserves the intended `this` binding.",
  ),
  q(
    "w5-q9",
    "identify-error",
    "variables",
    "What's wrong here?",
    [
      "Nothing, this works fine",
      "let is hoisted into a temporal dead zone — accessing it before its line throws",
      "console.log can't run before variable declarations",
      "score should be a string",
    ],
    1,
    "let/const are hoisted but remain uninitialized until their declaration line executes, throwing a ReferenceError if accessed earlier.",
    "console.log(score);\nlet score = 10;",
  ),
  q(
    "w5-q10",
    "true-false",
    "objects",
    "Every object's prototype chain eventually ends at Object.prototype, then null.",
    ["True", "False"],
    0,
    "The chain terminates at null, which is why property lookups eventually stop instead of looping forever.",
  ),
];

const week6: QuizQuestion[] = [
  q(
    "w6-q1",
    "predict-output",
    "async",
    "In what order do these log?",
    ["1, 2, 3", "1, 3, 2", "2, 1, 3", "3, 1, 2"],
    1,
    "Synchronous code (1, 3) always runs before a deferred timer callback (2), regardless of delay.",
    'console.log("1");\nsetTimeout(() => console.log("2"), 0);\nconsole.log("3");',
  ),
  q(
    "w6-q2",
    "true-false",
    "async",
    "A Promise can settle (fulfill or reject) more than once.",
    ["True", "False"],
    1,
    "A Promise transitions from pending to settled exactly once, and that outcome is permanent.",
  ),
  q(
    "w6-q3",
    "identify-error",
    "promises",
    "What's wrong with this chain?",
    [
      "Nothing is wrong",
      "The first .then() doesn't return a value, so the next .then() receives undefined",
      "Promises can't be chained twice",
      ".then() must always throw",
    ],
    1,
    "Every .then() callback must explicitly return a value to pass it down the chain — this one falls off the end.",
    "Promise.resolve(5)\n  .then((n) => { n * 2; })\n  .then((result) => console.log(result));",
  ),
  q(
    "w6-q4",
    "multiple-choice",
    "promises",
    "What happens if one Promise passed to Promise.all rejects?",
    [
      "Promise.all ignores it",
      "Promise.all immediately rejects with that error",
      "It waits for the others regardless",
      "It retries automatically",
    ],
    1,
    "Promise.all is all-or-nothing — a single rejection rejects the combined Promise right away.",
  ),
  q(
    "w6-q5",
    "predict-output",
    "async",
    "In what order do these log?",
    ["A, B, C, D", "A, D, C, B", "A, D, B, C", "D, A, C, B"],
    1,
    "Sync code runs first (A, D), then queued microtasks (C, a Promise), then the macrotask (B, a timer).",
    'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");',
  ),
  q(
    "w6-q6",
    "true-false",
    "apis",
    "fetch() rejects its returned Promise when the server responds with a 404.",
    ["True", "False"],
    1,
    "fetch only rejects on network-level failure; HTTP error statuses still resolve successfully and must be checked via response.ok.",
  ),
  q(
    "w6-q7",
    "select-code",
    "async",
    "Which correctly awaits a fetch and checks for failure?",
    [
      "const r = fetch(url); if (r.ok) ...",
      "const r = await fetch(url); if (!r.ok) throw new Error();",
      "fetch(url).ok",
      "await r = fetch(url)",
    ],
    1,
    "await the fetch call first, then explicitly check response.ok before trusting the result.",
  ),
  q(
    "w6-q8",
    "scenario",
    "promises",
    "You need to load a user and their posts, which don't depend on each other. What's the most efficient approach?",
    [
      "Await the user, then await the posts sequentially",
      "Promise.all([loadUser(), loadPosts()])",
      "Load posts first always",
      "They must be loaded one at a time",
    ],
    1,
    "Independent requests running concurrently via Promise.all finish faster than awaiting them one after another.",
  ),
  q(
    "w6-q9",
    "identify-error",
    "async",
    "Why does this crash?",
    [
      "Promise.resolve is misspelled",
      "Missing `await`, so value is still a pending Promise, not a string",
      "toUpperCase doesn't exist",
      "There is no bug",
    ],
    1,
    "Without await, `value` holds the Promise object itself, which has no toUpperCase method.",
    'async function loadName() {\n  const value = Promise.resolve("Ada");\n  return value.toUpperCase();\n}',
  ),
  q(
    "w6-q10",
    "multiple-choice",
    "async",
    "Besides loading and success, what other UI state do real fetches need to handle explicitly?",
    [
      "Nothing else is needed",
      "Error, and often empty",
      "Only a spinner",
      "A confirmation dialog",
    ],
    1,
    "Networks fail and empty results happen — both deserve their own explicit, user-visible state.",
  ),
];

const week7: QuizQuestion[] = [
  q(
    "w7-q1",
    "multiple-choice",
    "architecture",
    "What is a strong signal a function should be split into smaller ones?",
    [
      "It has a short name",
      "It does several unrelated things or is hard to summarize in one sentence",
      "It has any parameters",
      "It's called more than once",
    ],
    1,
    "A function that's hard to describe in one clear sentence is usually doing too much.",
  ),
  q(
    "w7-q2",
    "true-false",
    "functions",
    "Debounce guarantees a function runs at least once per fixed interval.",
    ["True", "False"],
    1,
    "That describes throttle — debounce instead waits for a pause in calls before running once.",
  ),
  q(
    "w7-q3",
    "identify-error",
    "algorithms",
    "What performance problem does this have?",
    [
      "No problem — it's O(n)",
      "The nested loop makes it O(n²)",
      "It will throw an error",
      "Arrays can't be compared this way",
    ],
    1,
    "Comparing every element against every other element in nested loops over the same data is a classic O(n²) pattern.",
    "function hasDuplicate(list) {\n  for (let i = 0; i < list.length; i++) {\n    for (let j = 0; j < list.length; j++) {\n      if (i !== j && list[i] === list[j]) return true;\n    }\n  }\n  return false;\n}",
  ),
  q(
    "w7-q4",
    "select-code",
    "algorithms",
    "Which data structure gives O(1) membership checks for a large list of values?",
    [
      "A plain array with .includes()",
      "A Set",
      "A sorted array with linear search",
      "A string",
    ],
    1,
    "Set uses hashing internally, making .has() checks constant time regardless of size.",
  ),
  q(
    "w7-q5",
    "predict-output",
    "functions",
    "How many times does calls increment?",
    ["0", "1", "2", "4"],
    1,
    "The second call with the same argument (4) is served from the memoization cache instead of recomputing.",
    "let calls = 0;\nconst square = memoize((n) => { calls++; return n * n; });\nsquare(4);\nsquare(4);\nconsole.log(calls);",
  ),
  q(
    "w7-q6",
    "true-false",
    "testing",
    "An automated test's main value is that it catches regressions automatically and repeatably.",
    ["True", "False"],
    0,
    "Tests encode expected behavior so future changes that break it fail loudly, without manual re-checking.",
  ),
  q(
    "w7-q7",
    "scenario",
    "architecture",
    "Why do professional teams use feature branches instead of committing directly to main?",
    [
      "Branches are required by npm",
      "It isolates in-progress work and enables review before merging",
      "It makes Git run faster",
      "There's no real reason",
    ],
    1,
    "Feature branches let work be reviewed, tested, and discussed in a pull request before reaching main.",
  ),
  q(
    "w7-q8",
    "multiple-choice",
    "algorithms",
    "What does Big O primarily describe?",
    [
      "Exact runtime in milliseconds",
      "How work grows as input size grows",
      "The number of lines of code",
      "Memory usage only",
    ],
    1,
    "Big O describes the shape of growth as input size increases, ignoring constant factors.",
  ),
  q(
    "w7-q9",
    "identify-error",
    "functions",
    "What's the bug in this debounce implementation?",
    [
      "Nothing is wrong",
      "It never clears the previous timer, so every call still fires",
      "setTimeout doesn't accept a delay",
      "Arrow functions can't be debounced",
    ],
    1,
    "Without clearTimeout on every call, each previous pending call still fires — no calls are actually collapsed.",
    "function debounce(fn, delay) {\n  return (...args) => {\n    setTimeout(() => fn(...args), delay);\n  };\n}",
  ),
  q(
    "w7-q10",
    "true-false",
    "architecture",
    "Committing a real API key directly into a source file is a safe practice as long as the repository is private.",
    ["True", "False"],
    1,
    "Anything committed to Git remains in history indefinitely, even after later deletion — secrets belong in environment variables, not source code.",
  ),
];

const week8: QuizQuestion[] = [
  q(
    "w8-q1",
    "multiple-choice",
    "architecture",
    "Why should secrets live in environment variables instead of source code?",
    [
      "Environment variables are faster",
      "Source code is committed to Git history and often shared",
      "It's required by JavaScript syntax",
      "There's no real difference",
    ],
    1,
    "Anything committed to Git can persist in history forever, even if later deleted.",
  ),
  q(
    "w8-q2",
    "true-false",
    "architecture",
    "Client-side validation alone is sufficient for application security.",
    ["True", "False"],
    1,
    "Client-side code can be bypassed entirely by calling the API directly — the server must always validate too.",
  ),
  q(
    "w8-q3",
    "identify-error",
    "dom",
    "What accessibility problem does this button have?",
    [
      "Nothing is wrong",
      "An icon-only button with no accessible label announces nothing to screen readers",
      "Buttons can't contain icons",
      "onClick doesn't work on buttons",
    ],
    1,
    "An aria-label (or visually-hidden text) is needed so screen readers can announce the button's purpose.",
    "<button onClick={close}>\n  <XIcon />\n</button>",
  ),
  q(
    "w8-q4",
    "scenario",
    "architecture",
    "What should happen before optimizing a slow-feeling page?",
    [
      "Guess which part is slow and rewrite it",
      "Measure with a tool like Lighthouse to find the real bottleneck",
      "Remove all images immediately",
      "Switch frameworks",
    ],
    1,
    "Measurement targets the actual bottleneck; guessing often optimizes something that was never the problem.",
  ),
  q(
    "w8-q5",
    "true-false",
    "testing",
    "Running lint, typecheck, tests, and build automatically on every pull request replaces the need for code review.",
    ["True", "False"],
    1,
    "Automated checks catch regressions and typos, but human review still evaluates design, clarity, and intent.",
  ),
  q(
    "w8-q6",
    "select-code",
    "dom",
    "Which is more accessible for a clickable action?",
    [
      "<div onClick={...}>Save</div>",
      "<button onClick={...}>Save</button>",
      "<span onClick={...}>Save</span>",
      "<p onClick={...}>Save</p>",
    ],
    1,
    "A real <button> gets keyboard focus, Enter/Space activation, and screen reader semantics for free.",
  ),
  q(
    "w8-q7",
    "multiple-choice",
    "algorithms",
    "What do interviewers evaluate beyond whether your final code works?",
    [
      "Nothing else matters",
      "How you clarify the problem, communicate, and consider edge cases",
      "Typing speed",
      "Whether you memorized the answer",
    ],
    1,
    "Process — clarifying, communicating, and testing — is a core part of a technical interview's evaluation.",
  ),
  q(
    "w8-q8",
    "predict-output",
    "fundamentals",
    "What is the relationship between this course's JavaScript and React/Node.js?",
    [
      "They are unrelated languages",
      "React and Node.js build directly on these same JavaScript fundamentals",
      "You must forget JavaScript to learn them",
      "They require TypeScript first",
    ],
    1,
    "React components and Node.js servers are written in the same JavaScript — the fundamentals transfer directly.",
  ),
  q(
    "w8-q9",
    "identify-error",
    "architecture",
    "What's missing from this deploy checklist function?",
    [
      "Nothing is missing",
      "It should require every check to pass, not just some",
      "canDeploy shouldn't take an object",
      "Object.values doesn't exist",
    ],
    1,
    "Using .some() instead of .every() means deployment proceeds even if some checks failed — the opposite of intended.",
    "function canDeploy(checks) {\n  return Object.values(checks).some(Boolean);\n}",
  ),
  q(
    "w8-q10",
    "scenario",
    "architecture",
    "A production incident traces back to trusting unvalidated user input. What principle was violated?",
    [
      "Performance optimization",
      "Defensive coding — validating input before acting on it",
      "Code formatting standards",
      "Git branching strategy",
    ],
    1,
    "Defensive code validates assumptions about input explicitly instead of trusting it blindly.",
  ),
];

export const quizzes: WeeklyQuiz[] = [
  { week: 1, questions: week1 },
  { week: 2, questions: week2 },
  { week: 3, questions: week3 },
  { week: 4, questions: week4 },
  { week: 5, questions: week5 },
  { week: 6, questions: week6 },
  { week: 7, questions: week7 },
  { week: 8, questions: week8 },
];

export function getWeeklyQuiz(week: number) {
  return quizzes.find((quiz) => quiz.week === week);
}
